### ISSUE TITLE
App crashing at start up

### ISSUE THREAD

**Issue by astuter** [BelledonneCommunications/linphone-android#111]
I have downloaded the release source code version 3.2.7 & relevant binaries from linphone.org's Download section. I have added libraries of version 3.2.7 into release source code. When I try to run this source code, app is crashing at startup with following logs:

> 08-26 15:36:40.726 13872-13872/? I/art: Late-enabling -Xcheck:jni
08-26 15:36:40.747 13872-13872/? D/TidaProvider: TidaProvider()
08-26 15:36:40.806 13872-13872/org.linphone I/libthemeutils: Theme： libthemeutil.so load success
08-26 15:36:40.877 13872-13902/org.linphone D/OpenGLRenderer: Use EGL_SWAP_BEHAVIOR_PRESERVED: true
08-26 15:36:40.883 13872-13872/org.linphone D/ActivityThreadInjector: clearCachedDrawables.
08-26 15:36:40.893 13872-13872/org.linphone W/LinphoneCoreFactoryImpl: Unable to load optional library ffmpeg-linphone: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/org.linphone-1/base.apk"],nativeLibraryDirectories=[/data/app/org.linphone-1/lib/arm64, /data/app/org.linphone-1/base.apk!/lib/arm64-v8a, /vendor/lib64, /system/lib64]]] couldn't find "libffmpeg-linphone.so"
08-26 15:36:40.894 13872-13872/org.linphone D/AndroidRuntime: Shutting down VM
08-26 15:36:40.894 13872-13872/org.linphone E/AndroidRuntime: FATAL EXCEPTION: main
                                                              Process: org.linphone, PID: 13872
                                                              java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/org.linphone-1/base.apk"],nativeLibraryDirectories=[/data/app/org.linphone-1/lib/arm64, /data/app/org.linphone-1/base.apk!/lib/arm64-v8a, /vendor/lib64, /system/lib64]]] couldn't find "libbctoolbox.so"
                                                                  at java.lang.Runtime.loadLibrary(Runtime.java:367)
                                                                  at java.lang.System.loadLibrary(System.java:1076)
                                                                  at org.linphone.core.LinphoneCoreFactoryImpl.<clinit>(LinphoneCoreFactoryImpl.java:48)
                                                                  at java.lang.Class.classForName(Native Method)
                                                                  at java.lang.Class.forName(Class.java:324)
                                                                  at java.lang.Class.forName(Class.java:285)
                                                                  at org.linphone.core.LinphoneCoreFactory.instance(LinphoneCoreFactory.java:47)
                                                                  at org.linphone.LinphoneService.onCreate(LinphoneService.java:303)
                                                                  at android.app.ActivityThread.handleCreateService(ActivityThread.java:2884)
                                                                  at android.app.ActivityThread.access$1900(ActivityThread.java:153)
                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1434)
                                                                  at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                  at android.os.Looper.loop(Looper.java:148)
                                                                  at android.app.ActivityThread.main(ActivityThread.java:5441)
                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:738)
                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:628)
08-26 15:36:40.901 13872-13872/org.linphone I/Process: Sending signal. PID: 13872 SIG: 9

**Comment by duminkala** [comment]
I am getting the same crash problem. Any ideas?

**Comment by DatBewar** [comment]
Did this crash happen anymore now?

**Comment by astuter** [comment]
Hello @DatBewar,

I will check this tonight with latest source from master branch. I really need an input from your end. If I don't want to build linphone from source and just have to ready made binaries available from Andorid. What should be the proper steps or folder structure or  gradle configuration we should use, So that native library works well without any configuration issue. 

If you have any reference or guide for this, that will be really helpful.  If you find my question not clear, this is some kind of something what(Not actually) I'm asking: https://stackoverflow.com/q/15199027/2571277

**Comment by shaydvir** [comment]
I'm having the same error, does someone have any suggestions?

**Comment by MudraPatel** [comment]
Even I'm facing same issue
Exception:
Process: org.linphone, PID: 2010
    java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/org.linphone-1/base.apk"],nativeLibraryDirectories=[/data/app/org.linphone-1/lib/arm64, /vendor/lib64, /system/lib64]]] couldn't find "libgnustl_shared.so"
        at java.lang.Runtime.loadLibrary(Runtime.java:367)
        at java.lang.System.loadLibrary(System.java:1076)
        at org.linphone.core.LinphoneCoreFactoryImpl.<clinit>(LinphoneCoreFactoryImpl.java:46)
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:324)
        at java.lang.Class.forName(Class.java:285)
        at org.linphone.core.LinphoneCoreFactory.instance(LinphoneCoreFactory.java:47)
        at org.linphone.LinphoneService.onCreate(LinphoneService.java:300)
        at android.app.ActivityThread.handleCreateService(ActivityThread.java:3086)
        at android.app.ActivityThread.-wrap4(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1576)
        at android.os.Handler.dispatchMessage(Handler.java:111)
        at android.os.Looper.loop(Looper.java:207)
        at android.app.ActivityThread.main(ActivityThread.java:5769)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)

please help me

Thanks!

**Comment by astuter** [comment]
Hello @DatBewar,

Yes, still we are having this issue.

**Comment by judelove** [comment]
Did anyone ever find a solution to this? I had built quite some stuff on top of this and would not want to move to a 3rd SIP stack

**Comment by mehran22k** [comment]
Hi
i have the same error

App crashing at start up for android lower than 6

on run at device with android 5:

please help

mu debug log:

I/MultiDex: VM with version 2.1.0 has multidex support
    Installing application
    VM has multidex support, MultiDex support library is disabled.
I/InstantRun: starting instant run server: is main process
V/Monotype: SetAppTypeFace- try to flip, app = org.linphone
V/Monotype:     Typeface getFontPathFlipFont - systemFont = default#default
V/Monotype: SetAppTypeFace- try to flip, app = org.linphone
        Typeface getFontPathFlipFont - systemFont = default#default
D/OpenGLRenderer: Use EGL_SWAP_BEHAVIOR_PRESERVED: true
W/linker: libc++_shared.so: unused DT entry: type 0x6ffffffe arg 0x2b994
    libc++_shared.so: unused DT entry: type 0x6fffffff arg 0x2
W/FactoryImpl: Unable to load optional library ffmpeg-linphone: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/org.linphone-1/base.apk", zip file "/data/app/org.linphone-1/split_lib_dependencies_apk.apk", zip file "/data/app/org.linphone-1/split_lib_slice_0_apk.apk", zip file "/data/app/org.linphone-1/split_lib_slice_1_apk.apk", zip file "/data/app/org.linphone-1/split_lib_slice_2_apk.apk", zip file "/data/app/org.linphone-1/split_lib_slice_3_apk.apk", zip file "/data/app/org.linphone-1/split_lib_slice_4_apk.apk", zip file "/data/app/org.linphone-1/split_lib_slice_5_apk.apk", zip file "/data/app/org.linphone-1/split_lib_slice_6_apk.apk", zip file "/data/app/org.linphone-1/split_lib_slice_7_apk.apk", zip file "/data/app/org.linphone-1/split_lib_slice_8_apk.apk", zip file "/data/app/org.linphone-1/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/org.linphone-1/lib/arm, /vendor/lib, /system/lib]]] couldn't find "libffmpeg-linphone.so"
W/linker: libbctoolbox.so: unused DT entry: type 0x6ffffffe arg 0x1045c
    libbctoolbox.so: unused DT entry: type 0x6fffffff arg 0x2
W/linker: libortp.so: unused DT entry: type 0x6ffffffe arg 0x849c
W/linker: libortp.so: unused DT entry: type 0x6fffffff arg 0x3
W/linker: libmediastreamer.so: unused DT entry: type 0x6ffffffe arg 0x47634
    libmediastreamer.so: unused DT entry: type 0x6fffffff arg 0x3
W/linker: liblinphone.so: unused DT entry: type 0x6ffffffe arg 0x5055a0
W/linker: liblinphone.so: unused DT entry: type 0x6fffffff arg 0x3
Disconnected from the target VM, address: 'localhost:8600', transport: 'socket'
