### ISSUE TITLE
Linphone use_android_native_dialer Issue.

### ISSUE THREAD

**Issue by Adnan-addi** [BelledonneCommunications/linphone-android#1229]
Hi all.

I am working with the feature/use_android_native_dialer branch as we would like users to utilise that feature. However, there seems to be a problem. Whenever the user hangs up the call from the native dialler - the "Background mode" icon disappears from the top of the screen. If any call comes through within 5 minutes, the phone rings. After 5 minutes, the phone doesn't even ring and it seems Linphone is switched off in the background. There is no error in logcat. I am testing with an Android 9 phone.

When I click on Linphone after 5 min, I get the following error (might not be related):

2020-11-20 08:48:13.772 5837-5837/com.company.Packagename E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.company.Packagename, PID: 5837
    java.lang.RuntimeException: Unable to resume activity {com.company.Packagename/org.linphone.contacts.ContactsActivity}: java.lang.RuntimeException: LinphoneService not instantiated yet
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4039)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4071)
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:51)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1970)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7156)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)
     Caused by: java.lang.RuntimeException: LinphoneService not instantiated yet
        at org.linphone.LinphoneService.instance(LinphoneService.java:300)
        at org.linphone.activities.MainActivity.onResume(MainActivity.java:304)
        at org.linphone.contacts.ContactsActivity.onResume(ContactsActivity.java:92)
        at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1416)
        at android.app.Activity.performResume(Activity.java:7612)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4031)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4071)
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:51)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1970)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7156)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)

Appreciate your help!

**Comment by Viish** [comment]
That isn't related to the user of native dialer.
For a service to be kept alive on Android, it must be a foreground service, which means you have to create a notification for it.
Anyway the best way is to rely on push notifications to wake up the app when a call is received instead of trying to keep the app alive at all times.
