### ISSUE TITLE
prepare.py error

### ISSUE THREAD

**Issue by sengghee** [BelledonneCommunications/linphone-android#1264]
Hi:
I have this error when I run prepare.py
I have the last NDK(r21d) downloaded from Android Studio and ANDROID_NDK environment configured with PATH set to this environment.

Traceback (most recent call last):
  File "./prepare.py", line 435, in <module>
    sys.exit(main())
  File "./prepare.py", line 429, in main
    if preparator.check_environment() != 0:
  File "./prepare.py", line 173, in check_environment
    ret_ndk = self.check_ndk_version()
  File "./prepare.py", line 159, in check_ndk_version
    version = int(res.group(2))
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by Viish** [comment]
Hi,
Please update your repository, prepare.py no longer exists.
Cheers,
