### ISSUE TITLE
No Incoming Call Ringtone When "Use device ringtone" Enabled

### ISSUE THREAD

**Issue by ailicic** [BelledonneCommunications/linphone-android#1419]
If I enable the "Use device ringtone" setting in the Linphone "Call Settings" then the phone does not ring (the Linphone default ringtone works fine if I disable it). The default ringtone selected in the Android OS is the built-in "Bell Phone" ringtone. This ringtone plays fine from the Android OS settings.

Logcat shows the following error when I use the device ringtone and an incoming call is received:

```
2021-06-06 08:12:04.465 1538-8340/? I/MediaFocusControl: requestAudioFocus() from uid/pid 10293/2578 clientId=android.media.AudioManager@618f29forg.linphone.core.tools.audio.AudioHelper@885efec callingPack=org.linphone req=4 flags=0x0 sdk=29
2021-06-06 08:12:04.468 2578-2578/? W/System.err:     at org.linphone.core.tools.audio.AudioHelper.startRinging(AudioHelper.java:14)
2021-06-06 08:12:04.468 2578-2578/? W/System.err:     at org.linphone.core.tools.service.CoreManager$3.onCallStateChanged(CoreManager.java:5)
2021-06-06 08:12:04.468 2578-2578/? W/System.err:     at org.linphone.core.CoreImpl.iterate(Native Method)
2021-06-06 08:12:04.468 2578-2578/? W/System.err:     at org.linphone.core.CoreImpl.iterate(Core.java:1)
2021-06-06 08:12:04.468 2578-2578/? W/System.err:     at d.a.b$c.run(LinphoneManager.java:2)
```

**Please complete the following information**
 - Device: OnePlus 5
 - OS: Android 11
 - Version of the App: 4.4.3
 - Version of the SDK: N/A

**Comment by Viish** [comment]
Can you attach the whole logcat file please?

**Comment by ailicic** [comment]
Sure.
```
2021-06-06 12:27:21.504 1538-13011/? I/ActivityTaskManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=org.linphone/.activities.LinphoneLauncherActivity bnds=[234,1679][438,1915]} from uid 1000
2021-06-06 12:27:21.593 1538-1562/? D/ArtManagerInternalImpl: /data/misc/iorapd/org.linphone/4403/org.linphone.contacts.ContactsActivity/compiled_traces/compiled_trace.pb doesn't exist
2021-06-06 12:27:28.635 1538-12995/? W/ActivityManager: Foreground service started from background can not have location/camera/microphone access: service org.linphone/.core.tools.service.CoreService
2021-06-06 12:27:28.645 1538-13011/? I/MediaFocusControl: requestAudioFocus() from uid/pid 10293/6728 clientId=android.media.AudioManager@32ca40dorg.linphone.core.tools.audio.AudioHelper@30bffc2 callingPack=org.linphone req=4 flags=0x0 sdk=29
2021-06-06 12:27:28.650 6728-6728/? W/System.err:     at org.linphone.core.tools.audio.AudioHelper.startRinging(AudioHelper.java:14)
2021-06-06 12:27:28.650 6728-6728/? W/System.err:     at org.linphone.core.tools.service.CoreManager$3.onCallStateChanged(CoreManager.java:5)
2021-06-06 12:27:28.650 6728-6728/? W/System.err:     at org.linphone.core.CoreImpl.iterate(Native Method)
2021-06-06 12:27:28.650 6728-6728/? W/System.err:     at org.linphone.core.CoreImpl.iterate(Core.java:1)
2021-06-06 12:27:28.650 6728-6728/? W/System.err:     at org.linphone.core.tools.service.CoreManager$1.run(CoreManager.java:2)
2021-06-06 12:27:28.849 1538-1538/? D/NotificationService: 0|org.linphone|9|null|10293: granting content://settings/system/notification_sound
2021-06-06 12:27:28.851 1538-1538/? D/NotificationService: 0|org.linphone|9|null|10293: granting content://settings/system/notification_sound
2021-06-06 12:27:28.869 2624-2624/? W/NotifBindPipeline: Row is not set so pipeline will not run. notif = 0|org.linphone|9|null|10293
2021-06-06 12:27:34.375 1538-13011/? I/MediaFocusControl: abandonAudioFocus() from uid/pid 10293/6728 clientId=android.media.AudioManager@32ca40dorg.linphone.core.tools.audio.AudioHelper@30bffc2
```

**Comment by Viish** [comment]
Yes. Please enable debug logs in advanced settings, restart app, reproduce issue and attach SDK logs (upload button in About page).

**Comment by ailicic** [comment]
Ok. Here is the generated log file
[60bd29c8206e2_e6834cbe5d943674381a.gz](https://github.com/BelledonneCommunications/linphone-android/files/6604850/60bd29c8206e2_e6834cbe5d943674381a.gz)

**Comment by Viish** [comment]
Seems like on your device `Settings.System.DEFAULT_RINGTONE_URI` isn't available...
Can you attach the whole logcat please?

**Comment by ailicic** [comment]
I can but I'll share this with you first:
```
$ adb shell settings list system|grep ringtone
ringtone=content://media/internal/audio/media/93?title=Bell%20Phone&canonical=1
ringtone_89302370323053822807=content://media/internal/audio/media/93?title=Bell%20Phone&canonical=1
ringtone_set=1
```
Also worth pointing out:
- This is a default built-in ringtone
- It plays fine when previewing it inside the Android OS sound settings

Let me know if you want more logs. I can collect them starting from a cold boot.

**Comment by Viish** [comment]
Please attach full logcat logs.

**Comment by ailicic** [comment]
Here are the full logs, starting from boot with debug enabled in Linphone
[log.txt](https://github.com/BelledonneCommunications/linphone-android/files/6645622/log.txt)

**Comment by Viish** [comment]
Thanks, that helps.
I'm working on a different way to play the device ringtone, hopefuly it will fix the issue you are having.
Cheers.

**Comment by Viish** [comment]
Fix has been merged in master branch of SDK, will be part of next beta / release versions.

**Comment by ailicic** [comment]
Cool. Thanks :tada:
