### ISSUE TITLE
4.6.0-alpha crashes on startup

### ISSUE THREAD

**Issue by brianjmurrell** [BelledonneCommunications/linphone-android#1445]
I installed the latest master/4.6.0-alpha on top of a previously working 4.5.0-alpha-ish release on my phone and now trying to start Linphone results in the following crash:

```
07-08 13:47:01.895 13964 13964 I [MyLinphone]: Application is being created
07-08 13:47:01.900 13964 13964 W FactoryImpl: Unable to load optional library ffmpeg-linphone: dlopen failed: library "libffmpeg-linphone.so" not found
07-08 13:47:01.912  1316  3093 D CompatibilityChangeReporter: Compat change id reported: 136274596; UID 10401; state: ENABLED
07-08 13:47:01.928 13964 13964 I MyLinphone: [Preferences] File /data/user/0/org.linphone.debug/files/.linphonerc already exists
07-08 13:47:01.928 13964 13964 I MyLinphone: [Preferences] Overriding /data/user/0/org.linphone.debug/files/linphonerc by linphonerc_factory asset
07-08 13:47:01.928 13964 13964 I MyLinphone: [Preferences] Overriding /data/user/0/org.linphone.debug/files/assistant_linphone_default_values by assistant_linphone_default_values asset
07-08 13:47:01.929 13964 13964 I MyLinphone: [Preferences] Overriding /data/user/0/org.linphone.debug/files/assistant_default_values by assistant_default_values asset
07-08 13:47:01.929 13964 13964 W MyLinphone: [Preferences] Can't move [/data/user/0/org.linphone.debug/files/linphone-log-history.db] to [/data/user/0/org.linphone.debug/files/call-history.db], source file doesn't exists
07-08 13:47:01.929 13964 13964 W MyLinphone: [Preferences] Can't move [/data/user/0/org.linphone.debug/files/zrtp_secrets] to [/data/user/0/org.linphone.debug/files/zrtp-secrets.db], source file doesn't exists
07-08 13:47:02.009   606   606 E KeyMasterHalDevice: Finish send cmd failed
07-08 13:47:02.009   606   606 E KeyMasterHalDevice: ret: 0
07-08 13:47:02.009   606   606 E KeyMasterHalDevice: resp->status: -30
07-08 13:47:02.011 13964 13964 W AndroidKeystoreAesGcm: encountered a potentially transient KeyStore error, will wait and retry
07-08 13:47:02.011 13964 13964 W AndroidKeystoreAesGcm: javax.crypto.AEADBadTagException
07-08 13:47:02.011 13964 13964 W AndroidKeystoreAesGcm: 	at android.security.keystore.AndroidKeyStoreCipherSpiBase.engineDoFinal(AndroidKeyStoreCipherSpiBase.java:517)
07-08 13:47:02.011 13964 13964 W AndroidKeystoreAesGcm: 	at javax.crypto.Cipher.doFinal(Cipher.java:2113)
07-08 13:47:02.011 13964 13964 W AndroidKeystoreAesGcm: 	at com.google.crypto.tink.integration.android.AndroidKeystoreAesGcm.decryptInternal(AndroidKeystoreAesGcm.java:115)
07-08 13:47:02.011 13964 13964 W AndroidKeystoreAesGcm: 	at com.google.crypto.tink.integration.android.AndroidKeystoreAesGcm.decrypt(AndroidKeystoreAesGcm.java:97)
07-08 13:47:02.011 13964 13964 W AndroidKeystoreAesGcm: 	at com.google.crypto.tink.KeysetHandle.decrypt(KeysetHandle.java:206)
07-08 13:47:02.011 13964 13964 W AndroidKeystoreAesGcm: 	at com.google.crypto.tink.KeysetHandle.read(KeysetHandle.java:107)
07-08 13:47:02.011 13964 13964 W AndroidKeystoreAesGcm: 	at com.google.crypto.tink.integration.android.AndroidKeysetManager$Builder.read(AndroidKeysetManager.java:311)
07-08 13:47:02.011 13964 13964 W AndroidKeystoreAesGcm: 	at com.google.crypto.tink.integration.android.AndroidKeysetManager$Builder.readOrGenerateNewKeyset(AndroidKeysetManager.java:287)
07-08 13:47:02.011 13964 13964 W AndroidKeystoreAesGcm: 	at com.google.crypto.tink.integration.android.AndroidKeysetManager$Builder.build(AndroidKeysetManager.java:238)
07-08 13:47:02.011 13964 13964 W AndroidKeystoreAesGcm: 	at androidx.security.crypto.EncryptedSharedPreferences.create(EncryptedSharedPreferences.java:155)
07-08 13:47:02.011 13964 13964 W AndroidKeystoreAesGcm: 	at androidx.security.crypto.EncryptedSharedPreferences.create(EncryptedSharedPreferences.java:120)
07-08 13:47:02.011 13964 13964 W AndroidKeystoreAesGcm: 	at org.linphone.core.CorePreferences$encryptedSharedPreferences$2.invoke(CorePreferences.kt:52)
07-08 13:47:02.011 13964 13964 W AndroidKeystoreAesGcm: 	at org.linphone.core.CorePreferences$encryptedSharedPreferences$2.invoke(CorePreferences.kt:33)
07-08 13:47:02.011 13964 13964 W AndroidKeystoreAesGcm: 	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
07-08 13:47:02.011 13964 13964 W AndroidKeystoreAesGcm: 	at org.linphone.core.CorePreferences.getEncryptedSharedPreferences(Unknown Source:2)
07-08 13:47:02.011 13964 13964 W AndroidKeystoreAesGcm: 	at org.linphone.core.CorePreferences.getVfsEnabled(CorePreferences.kt:60)
07-08 13:47:02.011 13964 13964 W AndroidKeystoreAesGcm: 	at org.linphone.LinphoneApplication$Companion.ensureCoreExists(LinphoneApplication.kt:47)
07-08 13:47:02.011 13964 13964 W AndroidKeystoreAesGcm: 	at org.linphone.LinphoneApplication$Companion.ensureCoreExists$default(LinphoneApplication.kt:35)
07-08 13:47:02.011 13964 13964 W AndroidKeystoreAesGcm: 	at org.linphone.LinphoneApplication.onCreate(LinphoneApplication.kt:71)
07-08 13:47:02.011 13964 13964 W AndroidKeystoreAesGcm: 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1192)
07-08 13:47:02.011 13964 13964 W AndroidKeystoreAesGcm: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6719)
07-08 13:47:02.011 13964 13964 W AndroidKeystoreAesGcm: 	at android.app.ActivityThread.access$1300(ActivityThread.java:237)
07-08 13:47:02.011 13964 13964 W AndroidKeystoreAesGcm: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1913)
07-08 13:47:02.011 13964 13964 W AndroidKeystoreAesGcm: 	at android.os.Handler.dispatchMessage(Handler.java:106)
07-08 13:47:02.011 13964 13964 W AndroidKeystoreAesGcm: 	at android.os.Looper.loop(Looper.java:223)
07-08 13:47:02.011 13964 13964 W AndroidKeystoreAesGcm: 	at android.app.ActivityThread.main(ActivityThread.java:7664)
07-08 13:47:02.011 13964 13964 W AndroidKeystoreAesGcm: 	at java.lang.reflect.Method.invoke(Native Method)
07-08 13:47:02.011 13964 13964 W AndroidKeystoreAesGcm: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
07-08 13:47:02.011 13964 13964 W AndroidKeystoreAesGcm: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
07-08 13:47:02.011 13964 13964 W AndroidKeystoreAesGcm: Caused by: android.security.KeyStoreException: Signature/MAC verification failed
07-08 13:47:02.011 13964 13964 W AndroidKeystoreAesGcm: 	at android.security.KeyStore.getKeyStoreException(KeyStore.java:1301)
07-08 13:47:02.011 13964 13964 W AndroidKeystoreAesGcm: 	at android.security.keystore.KeyStoreCryptoOperationChunkedStreamer.doFinal(KeyStoreCryptoOperationChunkedStreamer.java:176)
07-08 13:47:02.011 13964 13964 W AndroidKeystoreAesGcm: 	at android.security.keystore.AndroidKeyStoreAuthenticatedAESCipherSpi$BufferAllOutputUntilDoFinalStreamer.doFinal(AndroidKeyStoreAuthenticatedAESCipherSpi.java:373)
07-08 13:47:02.011 13964 13964 W AndroidKeystoreAesGcm: 	at android.security.keystore.AndroidKeyStoreCipherSpiBase.engineDoFinal(AndroidKeyStoreCipherSpiBase.java:506)
07-08 13:47:02.011 13964 13964 W AndroidKeystoreAesGcm: 	... 28 more
07-08 13:47:02.070   606   606 E KeyMasterHalDevice: Finish send cmd failed
07-08 13:47:02.070   606   606 E KeyMasterHalDevice: ret: 0
07-08 13:47:02.070   606   606 E KeyMasterHalDevice: resp->status: -30
07-08 13:47:02.071 13964 13964 W AndroidKeysetManager: cannot decrypt keyset: 
07-08 13:47:02.071 13964 13964 W AndroidKeysetManager: javax.crypto.AEADBadTagException
07-08 13:47:02.071 13964 13964 W AndroidKeysetManager: 	at android.security.keystore.AndroidKeyStoreCipherSpiBase.engineDoFinal(AndroidKeyStoreCipherSpiBase.java:517)
07-08 13:47:02.071 13964 13964 W AndroidKeysetManager: 	at javax.crypto.Cipher.doFinal(Cipher.java:2113)
07-08 13:47:02.071 13964 13964 W AndroidKeysetManager: 	at com.google.crypto.tink.integration.android.AndroidKeystoreAesGcm.decryptInternal(AndroidKeystoreAesGcm.java:115)
07-08 13:47:02.071 13964 13964 W AndroidKeysetManager: 	at com.google.crypto.tink.integration.android.AndroidKeystoreAesGcm.decrypt(AndroidKeystoreAesGcm.java:101)
07-08 13:47:02.071 13964 13964 W AndroidKeysetManager: 	at com.google.crypto.tink.KeysetHandle.decrypt(KeysetHandle.java:206)
07-08 13:47:02.071 13964 13964 W AndroidKeysetManager: 	at com.google.crypto.tink.KeysetHandle.read(KeysetHandle.java:107)
07-08 13:47:02.071 13964 13964 W AndroidKeysetManager: 	at com.google.crypto.tink.integration.android.AndroidKeysetManager$Builder.read(AndroidKeysetManager.java:311)
07-08 13:47:02.071 13964 13964 W AndroidKeysetManager: 	at com.google.crypto.tink.integration.android.AndroidKeysetManager$Builder.readOrGenerateNewKeyset(AndroidKeysetManager.java:287)
07-08 13:47:02.071 13964 13964 W AndroidKeysetManager: 	at com.google.crypto.tink.integration.android.AndroidKeysetManager$Builder.build(AndroidKeysetManager.java:238)
07-08 13:47:02.071 13964 13964 W AndroidKeysetManager: 	at androidx.security.crypto.EncryptedSharedPreferences.create(EncryptedSharedPreferences.java:155)
07-08 13:47:02.071 13964 13964 W AndroidKeysetManager: 	at androidx.security.crypto.EncryptedSharedPreferences.create(EncryptedSharedPreferences.java:120)
07-08 13:47:02.071 13964 13964 W AndroidKeysetManager: 	at org.linphone.core.CorePreferences$encryptedSharedPreferences$2.invoke(CorePreferences.kt:52)
07-08 13:47:02.071 13964 13964 W AndroidKeysetManager: 	at org.linphone.core.CorePreferences$encryptedSharedPreferences$2.invoke(CorePreferences.kt:33)
07-08 13:47:02.071 13964 13964 W AndroidKeysetManager: 	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
07-08 13:47:02.071 13964 13964 W AndroidKeysetManager: 	at org.linphone.core.CorePreferences.getEncryptedSharedPreferences(Unknown Source:2)
07-08 13:47:02.071 13964 13964 W AndroidKeysetManager: 	at org.linphone.core.CorePreferences.getVfsEnabled(CorePreferences.kt:60)
07-08 13:47:02.071 13964 13964 W AndroidKeysetManager: 	at org.linphone.LinphoneApplication$Companion.ensureCoreExists(LinphoneApplication.kt:47)
07-08 13:47:02.071 13964 13964 W AndroidKeysetManager: 	at org.linphone.LinphoneApplication$Companion.ensureCoreExists$default(LinphoneApplication.kt:35)
07-08 13:47:02.071 13964 13964 W AndroidKeysetManager: 	at org.linphone.LinphoneApplication.onCreate(LinphoneApplication.kt:71)
07-08 13:47:02.071 13964 13964 W AndroidKeysetManager: 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1192)
07-08 13:47:02.071 13964 13964 W AndroidKeysetManager: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6719)
07-08 13:47:02.071 13964 13964 W AndroidKeysetManager: 	at android.app.ActivityThread.access$1300(ActivityThread.java:237)
07-08 13:47:02.071 13964 13964 W AndroidKeysetManager: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1913)
07-08 13:47:02.071 13964 13964 W AndroidKeysetManager: 	at android.os.Handler.dispatchMessage(Handler.java:106)
07-08 13:47:02.071 13964 13964 W AndroidKeysetManager: 	at android.os.Looper.loop(Looper.java:223)
07-08 13:47:02.071 13964 13964 W AndroidKeysetManager: 	at android.app.ActivityThread.main(ActivityThread.java:7664)
07-08 13:47:02.071 13964 13964 W AndroidKeysetManager: 	at java.lang.reflect.Method.invoke(Native Method)
07-08 13:47:02.071 13964 13964 W AndroidKeysetManager: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
07-08 13:47:02.071 13964 13964 W AndroidKeysetManager: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
07-08 13:47:02.071 13964 13964 W AndroidKeysetManager: Caused by: android.security.KeyStoreException: Signature/MAC verification failed
07-08 13:47:02.071 13964 13964 W AndroidKeysetManager: 	at android.security.KeyStore.getKeyStoreException(KeyStore.java:1301)
07-08 13:47:02.071 13964 13964 W AndroidKeysetManager: 	at android.security.keystore.KeyStoreCryptoOperationChunkedStreamer.doFinal(KeyStoreCryptoOperationChunkedStreamer.java:176)
07-08 13:47:02.071 13964 13964 W AndroidKeysetManager: 	at android.security.keystore.AndroidKeyStoreAuthenticatedAESCipherSpi$BufferAllOutputUntilDoFinalStreamer.doFinal(AndroidKeyStoreAuthenticatedAESCipherSpi.java:373)
07-08 13:47:02.071 13964 13964 W AndroidKeysetManager: 	at android.security.keystore.AndroidKeyStoreCipherSpiBase.engineDoFinal(AndroidKeyStoreCipherSpiBase.java:506)
07-08 13:47:02.071 13964 13964 W AndroidKeysetManager: 	... 28 more
07-08 13:47:02.073 13964 13964 D AndroidRuntime: Shutting down VM
07-08 13:47:02.074 13964 13964 E AndroidRuntime: FATAL EXCEPTION: main
07-08 13:47:02.074 13964 13964 E AndroidRuntime: Process: org.linphone.debug, PID: 13964
07-08 13:47:02.074 13964 13964 E AndroidRuntime: java.lang.RuntimeException: Unable to create application org.linphone.LinphoneApplication: com.google.crypto.tink.shaded.protobuf.InvalidProtocolBufferException: Protocol message contained an invalid tag (zero).
07-08 13:47:02.074 13964 13964 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6724)
07-08 13:47:02.074 13964 13964 E AndroidRuntime: 	at android.app.ActivityThread.access$1300(ActivityThread.java:237)
07-08 13:47:02.074 13964 13964 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1913)
07-08 13:47:02.074 13964 13964 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
07-08 13:47:02.074 13964 13964 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:223)
07-08 13:47:02.074 13964 13964 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7664)
07-08 13:47:02.074 13964 13964 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-08 13:47:02.074 13964 13964 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
07-08 13:47:02.074 13964 13964 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
07-08 13:47:02.074 13964 13964 E AndroidRuntime: Caused by: com.google.crypto.tink.shaded.protobuf.InvalidProtocolBufferException: Protocol message contained an invalid tag (zero).
07-08 13:47:02.074 13964 13964 E AndroidRuntime: 	at com.google.crypto.tink.shaded.protobuf.GeneratedMessageLite.parsePartialFrom(GeneratedMessageLite.java:1566)
07-08 13:47:02.074 13964 13964 E AndroidRuntime: 	at com.google.crypto.tink.shaded.protobuf.GeneratedMessageLite.parseFrom(GeneratedMessageLite.java:1664)
07-08 13:47:02.074 13964 13964 E AndroidRuntime: 	at com.google.crypto.tink.proto.Keyset.parseFrom(Keyset.java:957)
07-08 13:47:02.074 13964 13964 E AndroidRuntime: 	at com.google.crypto.tink.integration.android.SharedPrefKeysetReader.read(SharedPrefKeysetReader.java:84)
07-08 13:47:02.074 13964 13964 E AndroidRuntime: 	at com.google.crypto.tink.CleartextKeysetHandle.read(CleartextKeysetHandle.java:58)
07-08 13:47:02.074 13964 13964 E AndroidRuntime: 	at com.google.crypto.tink.integration.android.AndroidKeysetManager$Builder.read(AndroidKeysetManager.java:328)
07-08 13:47:02.074 13964 13964 E AndroidRuntime: 	at com.google.crypto.tink.integration.android.AndroidKeysetManager$Builder.readOrGenerateNewKeyset(AndroidKeysetManager.java:287)
07-08 13:47:02.074 13964 13964 E AndroidRuntime: 	at com.google.crypto.tink.integration.android.AndroidKeysetManager$Builder.build(AndroidKeysetManager.java:238)
07-08 13:47:02.074 13964 13964 E AndroidRuntime: 	at androidx.security.crypto.EncryptedSharedPreferences.create(EncryptedSharedPreferences.java:155)
07-08 13:47:02.074 13964 13964 E AndroidRuntime: 	at androidx.security.crypto.EncryptedSharedPreferences.create(EncryptedSharedPreferences.java:120)
07-08 13:47:02.074 13964 13964 E AndroidRuntime: 	at org.linphone.core.CorePreferences$encryptedSharedPreferences$2.invoke(CorePreferences.kt:52)
07-08 13:47:02.074 13964 13964 E AndroidRuntime: 	at org.linphone.core.CorePreferences$encryptedSharedPreferences$2.invoke(CorePreferences.kt:33)
07-08 13:47:02.074 13964 13964 E AndroidRuntime: 	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
07-08 13:47:02.074 13964 13964 E AndroidRuntime: 	at org.linphone.core.CorePreferences.getEncryptedSharedPreferences(Unknown Source:2)
07-08 13:47:02.074 13964 13964 E AndroidRuntime: 	at org.linphone.core.CorePreferences.getVfsEnabled(CorePreferences.kt:60)
07-08 13:47:02.074 13964 13964 E AndroidRuntime: 	at org.linphone.LinphoneApplication$Companion.ensureCoreExists(LinphoneApplication.kt:47)
07-08 13:47:02.074 13964 13964 E AndroidRuntime: 	at org.linphone.LinphoneApplication$Companion.ensureCoreExists$default(LinphoneApplication.kt:35)
07-08 13:47:02.074 13964 13964 E AndroidRuntime: 	at org.linphone.LinphoneApplication.onCreate(LinphoneApplication.kt:71)
07-08 13:47:02.074 13964 13964 E AndroidRuntime: 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1192)
07-08 13:47:02.074 13964 13964 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6719)
07-08 13:47:02.074 13964 13964 E AndroidRuntime: 	... 8 more
```

**Comment by Viish** [comment]
Do you enabled VFS feature in advanced settings ?

**Comment by Viish** [comment]
Seems to be an issue with androidx.security:security-crypto package.
I recommend you to clean your build, build again and if issue persists, uninstall and reinstall.

**Comment by brianjmurrell** [comment]
> Do you enabled VFS feature in advanced settings ?

It crashes **immediately** on startup, so I have no opportunity to enable/disable anything.

> I recommend you to clean your build,

What is the process to do this effectively?

**Comment by brianjmurrell** [comment]
I had to uninstall and re-install.  But that removed all of my previous conversations.  :frowning:

**Comment by Viish** [comment]
> I had to uninstall and re-install. But that removed all of my previous conversations. frowning

Yes, this is a side effect of uninstalling app.

Hope they will fix this issue in next version of security-crypto lib.

**Comment by brianjmurrell** [comment]
> Yes, this is a side effect of uninstalling app.

A very unfortunate one, that a warning about would be useful when you ask somebody to do that.

Is it really not possible to retain data from uninstall->install?  Or provide an export/import function to retain that data during uninstall->install?

> Hope they will fix this issue in next version of security-crypto lib.

If they do not, won't this mean **all** linphone users are going to experience this problem along with the undesirable workaround of having to uninstall->install and lose all of their data?

**Comment by Viish** [comment]
> If they do not, won't this mean all linphone users are going to experience this problem along with the undesirable workaround of having to uninstall->install and lose all of their data?

No, this is quite random actually...

> Is it really not possible to retain data from uninstall->install?

Yes you can do something like `adb shell-run as org.linphone[.debug] cat files/linphone.db > linphone.db` to save it and then restore it later following a similar process.

> Or provide an export/import function to retain that data during uninstall->install?

One day this will be a feature in the SDK & the app, but it isn't scheduled yet.
