### ISSUE TITLE
Crash when pressing back button while in call

### ISSUE THREAD

**Issue by JonWatson** [BelledonneCommunications/linphone-android#1466]
While a call is ongoing(CallActivity displayed), swipe up from the bottom to display system navigation bar.  Press the back button and observe crash

    java.lang.IllegalStateException: View androidx.core.widget.NestedScrollView{f517135 VFED..C.. ......ID 0,0-904,2170} does not have a NavController set
        at androidx.navigation.Navigation.findNavController(Navigation.java:84)
        at androidx.navigation.fragment.NavHostFragment.findNavController(NavHostFragment.java:120)
        at androidx.navigation.fragment.FragmentKt.findNavController(Fragment.kt:29)
        at org.linphone.activities.GenericFragment.goBack(GenericFragment.kt:88)
        at org.linphone.activities.GenericFragment.onBackPressed(GenericFragment.kt:83)
        at org.linphone.activities.GenericFragment$onBackPressedCallback$1.handleOnBackPressed(GenericFragment.kt:42)
        at androidx.activity.OnBackPressedDispatcher.onBackPressed(OnBackPressedDispatcher.java:192)
        at androidx.activity.ComponentActivity.onBackPressed(ComponentActivity.java:529)
        at android.app.Activity.onKeyUp(Activity.java:3784)
        at android.view.KeyEvent.dispatch(KeyEvent.java:2866)
        at android.app.Activity.dispatchKeyEvent(Activity.java:4090)

occurs on master (7db83a3ce)

**Comment by Viish** [comment]
Fixed in 30009e56
