### ISSUE TITLE
NullPointerException - As soon as the app installs and it opens it shows the error.

### ISSUE THREAD

**Issue by deeprathod** [BelledonneCommunications/linphone-android#149]
When i run the code, it shows me the following error in **LinphoneService.Class**. Tried all the ways, but no luck so far. Was anybody able to run it successfully ?. Thank in Advance. 

**Error: **
`FATAL EXCEPTION: main
                                                              Process: org.linphone, PID: 16080
                                                              java.lang.RuntimeException: Unable to create service org.linphone.LinphoneService: java.lang.NullPointerException
                                                                  at android.app.ActivityThread.handleCreateService(ActivityThread.java:2582)
                                                                  at android.app.ActivityThread.access$1800(ActivityThread.java:139)
                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1292)
                                                                  at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                  at android.os.Looper.loop(Looper.java:136)
                                                                  at android.app.ActivityThread.main(ActivityThread.java:5028)
                                                                  at java.lang.reflect.Method.invokeNative(Native Method)
                                                                  at java.lang.reflect.Method.invoke(Method.java:515)
                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:788)
                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:604)
                                                                  at dalvik.system.NativeStart.main(Native Method)
                                                               Caused by: java.lang.NullPointerException
                                                                  at org.linphone.LinphoneService.onCreate(LinphoneService.java:304)
                                                                  at android.app.ActivityThread.handleCreateService(ActivityThread.java:2572)
                                                                  at android.app.ActivityThread.access$1800(ActivityThread.java:139) 
                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1292) 
                                                                  at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                  at android.os.Looper.loop(Looper.java:136) 
                                                                  at android.app.ActivityThread.main(ActivityThread.java:5028) 
                                                                  at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                  at java.lang.reflect.Method.invoke(Method.java:515)`

**Comment by viet97** [comment]
can anyone solve this? pls i'm stuck cause of this problem

**Comment by Samuelyip74** [comment]
I have the same problem
