### ISSUE TITLE
Linphone crashes when Telecom manager is disabled

### ISSUE THREAD

**Issue by driesken** [BelledonneCommunications/linphone-android#1540]
With the latest build, after closing Linphone and swiping it from recents apps, it crashes during start. This behavior occurs if an account is configured and the telecom manager option is not enabled.

All permissions have been granted.

> 10-31 19:06:50.121  1708  1708 I belle-sip: Resolver is not using connect().
> 10-31 19:06:50.121  1708  1708 I belle-sip: resolver_process_data dns_res_check() in progress
> 10-31 19:06:50.121  1708  1708 I belle-sip: DNS resolution awaiting response, queued to main loop
> 10-31 19:06:50.122  1708  1708 I linphone-android: [Context] Configuring Core10-31 19:06:50.124  1708  1708 I linphone-android: [Context] Core configured
> 10-31 19:06:50.125  1708  1708 D AndroidRuntime: Shutting down VM
> 10-31 19:06:50.125  1708  1708 E AndroidRuntime: FATAL EXCEPTION: main
> 10-31 19:06:50.125  1708  1708 E AndroidRuntime: Process: be.uzgent.uzlinphone, PID: 170810-31 19:06:50.125  1708  1708 E AndroidRuntime: java.lang.RuntimeException: Unable to create application org.linphone.LinphoneApplication: java.lang.NullPointerException10-31 19:06:50.125  1708  1708 E AndroidRuntime:        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7578)
> 10-31 19:06:50.125  1708  1708 E AndroidRuntime:        at android.app.ActivityThread.access$1500(ActivityThread.java:301)
> 10-31 19:06:50.125  1708  1708 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2166)
> 10-31 19:06:50.125  1708  1708 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
> 10-31 19:06:50.125  1708  1708 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:246)
> 10-31 19:06:50.125  1708  1708 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:8633)
> 10-31 19:06:50.125  1708  1708 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
> 10-31 19:06:50.125  1708  1708 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)10-31 19:06:50.125  1708  1708 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)10-31 19:06:50.125  1708  1708 E AndroidRuntime: Caused by: java.lang.NullPointerException
> 10-31 19:06:50.125  1708  1708 E AndroidRuntime:        at org.linphone.utils.SingletonHolder.get(SingletonHolder.kt:38)
> 10-31 19:06:50.125  1708  1708 E AndroidRuntime:        at org.linphone.core.CoreContext.initPhoneStateListener(CoreContext.kt:422)
> 10-31 19:06:50.125  1708  1708 E AndroidRuntime:        at org.linphone.core.CoreContext.start(CoreContext.kt:330)
> 10-31 19:06:50.125  1708  1708 E AndroidRuntime:        at org.linphone.core.CoreContext.start$default(CoreContext.kt:307)
> 10-31 19:06:50.125  1708  1708 E AndroidRuntime:        at org.linphone.LinphoneApplication$Companion.ensureCoreExists(LinphoneApplication.kt:63)
> 10-31 19:06:50.125  1708  1708 E AndroidRuntime:        at org.linphone.LinphoneApplication$Companion.ensureCoreExists$default(LinphoneApplication.kt:35)10-31 19:06:50.125  1708  1708 E AndroidRuntime:        at org.linphone.LinphoneApplication.onCreate(LinphoneApplication.kt:71)10-31 19:06:50.125  1708  1708 E AndroidRuntime:        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1192)10-31 19:06:50.125  1708  1708 E AndroidRuntime:        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7573)
> 10-31 19:06:50.125  1708  1708 E AndroidRuntime:        ... 8 more
> 10-31 19:06:50.200  1708  1733 D libcrashlytics: Initializing libcrashlytics version 3.0.0
> 10-31 19:06:50.201  1708  1733 D libcrashlytics: Initializing native crash handling successful.
> 10-31 19:06:50.202  1708  1733 I FirebaseCrashlytics: Crashlytics NDK initialization successful

**Comment by Viish** [comment]
Thanks. Fixed in 19b15e2b3b91e3d355d18db88663cd1d47c65cee
