### ISSUE TITLE
Crashes at startup since version 4.6.0

### ISSUE THREAD

**Issue by Fregf** [BelledonneCommunications/linphone-android#1617]
I have installed Linphone from F-droid repository. Version 4.5.2 from F-Droid worked fine, however since updating it to version 4.6.0 from F-Droid, Linphone immediately crashes at startup and is unusable.

**Please complete the following information**
 - Device: Google Pixel 6
 - OS: Android 12
 - Version of the App: 4.6.0 from F-Droid

**Adb logcat logs**

```
02-19 14:20:09.973  1555  1634 I ActivityManager: Start proc 22757:org.linphone/u0a354 for service {org.linphone/org.linphone.core.CoreService}
02-19 14:20:10.029 22757 22757 V GraphicsEnvironment: ANGLE Developer option for 'org.linphone' set to: 'default'
02-19 14:20:10.029 22757 22757 V GraphicsEnvironment: ANGLE GameManagerService for org.linphone: false
02-19 14:20:10.040 22757 22757 W FactoryImpl: Unable to load optional library ffmpeg-linphone: dlopen failed: library "libffmpeg-linphone.so" not found
02-19 14:20:10.059 22757 22757 I Linphone: [Preferences] File /data/user/0/org.linphone/files/.linphonerc already exists
02-19 14:20:10.059 22757 22757 I Linphone: [Preferences] Overriding /data/user/0/org.linphone/files/linphonerc by linphonerc_factory asset
02-19 14:20:10.060 22757 22757 I Linphone: [Preferences] Overriding /data/user/0/org.linphone/files/assistant_linphone_default_values by assistant_linphone_default_values asset
02-19 14:20:10.060 22757 22757 I Linphone: [Preferences] Overriding /data/user/0/org.linphone/files/assistant_default_values by assistant_default_values asset
02-19 14:20:10.060 22757 22757 W Linphone: [Preferences] Can't move [/data/user/0/org.linphone/files/linphone-log-history.db] to [/data/user/0/org.linphone/files/call-history.db], source file doesn't exists
02-19 14:20:10.060 22757 22757 W Linphone: [Preferences] Can't move [/data/user/0/org.linphone/files/zrtp_secrets] to [/data/user/0/org.linphone/files/zrtp-secrets.db], source file doesn't exists
02-19 14:20:10.290  1555  3965 D ConnectivityService: requestNetwork for uid/pid:10354/22757 activeRequest: null callbackRequest: 4803 [NetworkRequest [ REQUEST id=4804, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VCN_MANAGED Uid: 10354 RequestorUid: 10354 RequestorPkg: org.linphone UnderlyingNetworks: Null] ]] callback flags: 0 order: 2147483647
02-19 14:20:10.294  1555  1779 D UntrustedWifiNetworkFactory: got request NetworkRequest [ REQUEST id=4804, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VCN_MANAGED Uid: 10354 RequestorUid: 10354 RequestorPkg: org.linphone UnderlyingNetworks: Null] ]
02-19 14:20:10.294  1555  1779 D OemPaidWifiNetworkFactory: got request NetworkRequest [ REQUEST id=4804, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VCN_MANAGED Uid: 10354 RequestorUid: 10354 RequestorPkg: org.linphone UnderlyingNetworks: Null] ]
02-19 14:20:10.309 22757 22757 E AndroidRuntime: FATAL EXCEPTION: main
02-19 14:20:10.309 22757 22757 E AndroidRuntime: Process: org.linphone, PID: 22757
02-19 14:20:10.309 22757 22757 E AndroidRuntime: java.lang.RuntimeException: Unable to start service org.linphone.core.CoreService@f4dc3ee with Intent { cmp=org.linphone/.core.CoreService }: java.lang.IllegalArgumentException: null notification
02-19 14:20:10.309 22757 22757 E AndroidRuntime: 	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4657)
02-19 14:20:10.309 22757 22757 E AndroidRuntime: 	at android.app.ActivityThread.access$2000(ActivityThread.java:247)
02-19 14:20:10.309 22757 22757 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2091)
02-19 14:20:10.309 22757 22757 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
02-19 14:20:10.309 22757 22757 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
02-19 14:20:10.309 22757 22757 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
02-19 14:20:10.309 22757 22757 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7839)
02-19 14:20:10.309 22757 22757 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
02-19 14:20:10.309 22757 22757 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
02-19 14:20:10.309 22757 22757 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
02-19 14:20:10.309 22757 22757 E AndroidRuntime: Caused by: java.lang.IllegalArgumentException: null notification
02-19 14:20:10.309 22757 22757 E AndroidRuntime: 	at android.os.Parcel.createExceptionOrNull(Parcel.java:2429)
02-19 14:20:10.309 22757 22757 E AndroidRuntime: 	at android.os.Parcel.createException(Parcel.java:2409)
02-19 14:20:10.309 22757 22757 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:2392)
02-19 14:20:10.309 22757 22757 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:2334)
02-19 14:20:10.309 22757 22757 E AndroidRuntime: 	at android.app.IActivityManager$Stub$Proxy.setServiceForeground(IActivityManager.java:7096)
02-19 14:20:10.309 22757 22757 E AndroidRuntime: 	at android.app.Service.startForeground(Service.java:733)
02-19 14:20:10.309 22757 22757 E AndroidRuntime: 	at o6.c.X(NotificationsManager.kt:5)
02-19 14:20:10.309 22757 22757 E AndroidRuntime: 	at org.linphone.core.CoreService.onStartCommand(CoreService.kt:3)
02-19 14:20:10.309 22757 22757 E AndroidRuntime: 	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4639)
02-19 14:20:10.309 22757 22757 E AndroidRuntime: 	... 9 more
02-19 14:20:10.309 22757 22757 E AndroidRuntime: Caused by: android.os.RemoteException: Remote stack trace:
02-19 14:20:10.309 22757 22757 E AndroidRuntime: 	at com.android.server.am.ActiveServices.setServiceForegroundInnerLocked(ActiveServices.java:1680)
02-19 14:20:10.309 22757 22757 E AndroidRuntime: 	at com.android.server.am.ActiveServices.setServiceForegroundLocked(ActiveServices.java:1350)
02-19 14:20:10.309 22757 22757 E AndroidRuntime: 	at com.android.server.am.ActivityManagerService.setServiceForeground(ActivityManagerService.java:11903)
02-19 14:20:10.309 22757 22757 E AndroidRuntime: 	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:3205)
02-19 14:20:10.309 22757 22757 E AndroidRuntime: 	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2498)
02-19 14:20:10.309 22757 22757 E AndroidRuntime: 
02-19 14:20:10.337  1555  3912 I ActivityManager: Process org.linphone (pid 22757) has died: prcp FGS 
02-19 14:20:10.337  1555  4194 D ConnectivityService: ConnectivityService NetworkRequestInfo binderDied(uid/pid:10354/22757, [NetworkRequest [ REQUEST id=4804, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VCN_MANAGED Uid: 10354 RequestorUid: 10354 RequestorPkg: org.linphone UnderlyingNetworks: Null] ]], android.os.BinderProxy@330dee7)
02-19 14:20:10.337  1555  1787 D ConnectivityService: releasing NetworkRequest [ REQUEST id=4804, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VCN_MANAGED Uid: 10354 RequestorUid: 10354 RequestorPkg: org.linphone UnderlyingNetworks: Null] ] (release request)
02-19 14:20:10.338  1555  3912 W ActivityManager: Scheduling restart of crashed service org.linphone/.core.CoreService in 1800000ms for start-requested
02-19 14:20:18.772  1555  1633 W ActivityManager: Bringing down service while still waiting for start foreground: ServiceRecord{20b8712 u0 org.linphone/.core.CoreService}


```

**Comment by vikilpet** [comment]
Same on Android 10

**Comment by Viish** [comment]
Hi,
Try with 4.6.1 release, it fixes some crashes and probably yours as well.
It's available on Play Store or as APK on our website https://linphone.org/releases/Android/

**Comment by Fregf** [comment]
Thanks for the pointer! I read the changelog: Crash when background mode was enabled and service notification channel was disabled. Re-enabling the service notification channel indeed works around the crash with 4.6.0, so this is indeed this problem. Thanks!
