### ISSUE TITLE
./prepare.py error

### ISSUE THREAD

**Issue by maddog05** [BelledonneCommunications/linphone-android#173]
Hi:
 I have this error when I run prepare.py
I have the last NDK(r16) downloaded from Android Studio and ANDROID_NDK environment configured

Traceback (most recent call last):
  File "./prepare.py", line 435, in <module>
    sys.exit(main())
  File "./prepare.py", line 429, in main
    if preparator.check_environment() != 0:
  File "./prepare.py", line 173, in check_environment
    ret_ndk = self.check_ndk_version()
  File "./prepare.py", line 159, in check_ndk_version
    version = int(res.group(2))
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by DatBewar** [comment]
Hello currently we don't support NDK16
Please use a NDK between 11 and 15

**Comment by maddog05** [comment]
Hi, thanks for your answer
