### ISSUE TITLE
Having so many java.lang.UnsatisfiedLinkError error

### ISSUE THREAD

**Issue by disolaterX** [BelledonneCommunications/linphone-android#1778]
Fatal Exception: java.lang.UnsatisfiedLinkError: No implementation found for void org.linphone.core.ConfigImpl.setInt(long, java.lang.String, java.lang.String, int) (tried android_disable_audio_route_changes
       at org.linphone.core.ConfigImpl.setInt(Config.java)
       at org.linphone.core.ConfigImpl.setInt(Config.java:858)
       at com.superfone.linphoneUtlis.CoreContext.registerSIPAccount(CoreContext.kt:875)
       at com.superfone.MyApplication.sipRegisterNormally(MyApplication.kt:426)
       at com.superfone.MyApplication.sipRefreshOrRegister(MyApplication.kt:194)
       at com.superfone.MyApplication.sipRefreshOrRegister$default(MyApplication.kt:191)
       at com.superfone.modules.superfonebase.SuperfoneService.callSipRegistration(SuperfoneService.kt:46)
       at com.superfone.modules.superfonebase.SuperfoneService.onCreate(SuperfoneService.kt:41)
       at android.app.ActivityThread.handleCreateService(ActivityThread.java:3803)
       at android.app.ActivityThread.access$1500(ActivityThread.java:237)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1894)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:224)
       at android.app.ActivityThread.main(ActivityThread.java:7081)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:928)

**Comment by Viish** [comment]
Check linphone SDK libraries are correctly loaded.
