### ISSUE TITLE
Unable to create service com.operrtel.service.LinphoneService

### ISSUE THREAD

**Issue by dishankEbizz** [BelledonneCommunications/linphone-android#1829]
Hello, 
I am facing below given issue in Android 13. Before it was working fine but suddenly got this issue. So can you please check and guide me for this?

Here are logs of the error:
```
Fatal Exception: java.lang.RuntimeException: Unable to create service com.operrtel.service.LinphoneService: java.lang.SecurityException: listen
       at android.app.ActivityThread.handleCreateService(ActivityThread.java:4528)
       at android.app.ActivityThread.-$$Nest$mhandleCreateService()
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2162)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:201)
       at android.os.Looper.loop(Looper.java:288)
       at android.app.ActivityThread.main(ActivityThread.java:7898)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

**Comment by Viish** [comment]
Hi dishankEbizz,

It seems to me you aren't respecting the terms of the GPLv3 license, so I won't help you.
I strongly recommend you to either comply with GPLv3 license or to buy a proprietary license from my company.
