### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by a2t2** [BelledonneCommunications/linphone-android#228]
I am trying to compile Linphone for arm64. I am using Debian. I have set my java and javac version to 1.8.

I am getting the following error:

test@Debian:~/Android/AndroidStudioProjects/Linphone/linphone-android$ ./prepare.py

FAILURE: Build failed with an exception.

* Where:
Build file '/home/test/Android/AndroidStudioProjects/Linphone/linphone-android/build.gradle' line: 38

* What went wrong:
A problem occurred evaluating root project 'linphone-android'.
**> java.lang.UnsupportedClassVersionError: com/android/build/gradle/AppPlugin : Unsupported major.minor version 52.0**

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s
 cmake /home/test/Android/AndroidStudioProjects/Linphone/linphone-android/submodules/cmake-builder -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_PREFIX_PATH=/home/test/Android/AndroidStudioProjects/Linphone/linphone-android/liblinphone-sdk/android-arm64 -DCMAKE_INSTALL_PREFIX=/home/test/Android/AndroidStudioProjects/Linphone/linphone-android/liblinphone-sdk/android-arm64 -DCMAKE_NO_SYSTEM_FROM_IMPORTED=YES -DLINPHONE_BUILDER_WORK_DIR=/home/test/Android/AndroidStudioProjects/Linphone/linphone-android/WORK/android-arm64 -DCMAKE_TOOLCHAIN_FILE=toolchains/toolchain-android-arm64.cmake -DCMAKE_INSTALL_MESSAGE=LAZY -DLINPHONE_BUILDER_CONFIG_FILE=configs/config-android.cmake -DLINPHONE_BUILDER_EXTERNAL_SOURCE_PATH=/home/test/Android/AndroidStudioProjects/Linphone/linphone-android/submodules -DLINPHONE_BUILDER_EXTERNAL_BUILDERS_PATH=/home/test/Android/AndroidStudioProjects/Linphone/linphone-android/cmake_builder

When I try to check with prepare.py --info, I get the following:

FAILURE: Build failed with an exception.

* Where:
Build file '/home/test/Android/AndroidStudioProjects/Linphone/linphone-android/build.gradle' line: 38

* What went wrong:
A problem occurred evaluating root project 'linphone-android'.
**> java.lang.UnsupportedClassVersionError: com/android/build/gradle/AppPlugin : Unsupported major.minor version 52.0**

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s
 cmake /home/test/Android/AndroidStudioProjects/Linphone/linphone-android/submodules/cmake-builder -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_PREFIX_PATH=/home/test/Android/AndroidStudioProjects/Linphone/linphone-android/liblinphone-sdk/android-arm64 -DCMAKE_INSTALL_PREFIX=/home/test/Android/AndroidStudioProjects/Linphone/linphone-android/liblinphone-sdk/android-arm64 -DCMAKE_NO_SYSTEM_FROM_IMPORTED=YES -DLINPHONE_BUILDER_WORK_DIR=/home/test/Android/AndroidStudioProjects/Linphone/linphone-android/WORK/android-arm64 -DCMAKE_TOOLCHAIN_FILE=toolchains/toolchain-android-arm64.cmake -DCMAKE_INSTALL_MESSAGE=LAZY -DLINPHONE_BUILDER_CONFIG_FILE=configs/config-android.cmake -DLINPHONE_BUILDER_EXTERNAL_SOURCE_PATH=/home/test/Android/AndroidStudioProjects/Linphone/linphone-android/submodules -DLINPHONE_BUILDER_EXTERNAL_BUILDERS_PATH=/home/test/Android/AndroidStudioProjects/Linphone/linphone-android/cmake_builder --info
CMake Error: The source directory "/home/test/Android/AndroidStudioProjects/Linphone/linphone-android/WORK/android-arm64/cmake/--info" does not exist.
Specify --help for usage, or press the help button on the CMake GUI.
Traceback (most recent call last):
  File "./prepare.py", line 463, in <module>
    sys.exit(main())
  File "./prepare.py", line 460, in main
    return preparator.run()
  File "submodules/cmake-builder/prepare.py", line 505, in run
    return self.prepare()
  File "./prepare.py", line 210, in prepare
    prepare.Preparator.prepare(self)
  File "submodules/cmake-builder/prepare.py", line 473, in prepare
    ret = self.target_prepare(self.targets[target_name])
  File "submodules/cmake-builder/prepare.py", line 444, in target_prepare
    content = open(cmakecache).read()
**IOError: [Errno 2] No such file or directory: '/home/test/Android/AndroidStudioProjects/Linphone/linphone-android/WORK/android-arm64/cmake/CMakeCache.txt'**

Does anyone know the solution ?
Thanks

**Comment by a2t2** [comment]
The problem was related my JAVA_HOME environment variable not set to my JDK 8 path.

export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64/
export PATH=$JAVA_HOME/bin:$JAVA_HOME/jre/bin:$PATH
export CLASSPATH=$CLASSPATH:$JAVA_HOME/lib:$JAVA_HOME/jre/lib
