### ISSUE TITLE
When running the project it gets crashed?

### ISSUE THREAD

**Issue by Harshjain2094** [BelledonneCommunications/linphone-android#231]
Getting this error when running the project for Android. Kindly do look into it as I need to build an app to app calling application in android.
And also ./prepare.py command gives an error that ndk build is not installed. I have looked on internet to but still was not able to solve this issue.

FATAL EXCEPTION: main Process: 
org.linphone, PID: 18336
 java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/org.linphone-1/base.apk"],nativeLibraryDirectories=[/data/app/org.linphone-1/lib/arm, /system/lib, /vendor/lib]]] couldn't find "libgnustl_shared.so"
at java.lang.Runtime.loadLibrary0(Runtime.java:984)
 at java.lang.System.loadLibrary(System.java:1562)
at org.linphone.core.LinphoneCoreFactoryImpl.<clinit>(LinphoneCoreFactoryImpl.java:46)
at java.lang.Class.classForName(Native Method)
at java.lang.Class.forName(Class.java:400)
at java.lang.Class.forName(Class.java:326)
at org.linphone.core.LinphoneCoreFactory.instance(LinphoneCoreFactory.java:47)
at org.linphone.LinphoneService.onCreate(LinphoneService.java:300)
at android.app.ActivityThread.handleCreateService(ActivityThread.java:3216)
 at android.app.ActivityThread.-wrap5(ActivityThread.java)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1586)
at android.os.Handler.dispatchMessage(Handler.java:102)
 at android.os.Looper.loop(Looper.java:154)
at android.app.ActivityThread.main(ActivityThread.java:6186)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)

Thanks in advance.

**Comment by rajazeeshanshaheen** [comment]
install ndk and give correct path,then run ./prepare.py

**Comment by Harshjain2094** [comment]
I did it.
There is one .so file it could not find it whatsoever I have tried?

**Comment by MudraPatel** [comment]
Even I'm facing the same issue
Could you please let me know if you got a solution @Harshjain2094 

Thanks!

**Comment by Harshjain2094** [comment]
@MudraPatel I don't know for sure if it is a proper solution but the ndk version I was using was 16.0 but it needed is a version 15 ndk so try to downgrade the version of ndk in android studio and I think it would clear the issue.

**Comment by MudraPatel** [comment]
@Harshjain2094  I did that but still, it's not working

Thanks!
