### ISSUE TITLE
H264 codec enabled in Android TV box, doesn't upload video stream 

### ISSUE THREAD

**Issue by arvinxian** [BelledonneCommunications/linphone-android#253]
I test the new linphone  for android in the android tv Box, when i use the H264 codec, linphone doesn't upload video stream, other device testd just get blank window (including pixel XL with android 8.1, mac etc.  but the video call between mac  and pixel Xl works fine. this issue just happened between the Android tv box and other devices)

the android tv box has the amlogic 905x cpu, the logcat's log seems show that the amlogic's encoder get problems, i googled it, but haven't get solution，

whats more， the VP8 codec works fine  between the Android tv box and other device，although the fps is low, maybe cause the vp8 don't use hardware encoder，

I looked up the logcat, it shows as blew
`E/ACodec: [OMX.amlogic.video.encoder.avc] storeMetaDataInBuffers (output) failed w/ err -2147483648
I/ACodec: [OMX.amlogic.video.encoder.avc] using color format 0x13 in place of 0x7f420888
I/ACodec: setupVideoEncoder succeeded
E/ACodec: [OMX.amlogic.video.encoder.avc] configureCodec returning error -2147483648
          signalError(omxError 0x80001001, internalError -2147483648)
E/MediaCodec: Codec reported err 0x80001001, actionCode 0, while in state 3
E/MediaCodec: configure failed with err 0x80001001, resetting...
I/OMXClient: Using client-side OMX mux.
W/System.err: android.media.MediaCodec$CodecException: Error 0x80001001
W/System.err:     at android.media.MediaCodec.native_configure(Native Method)
                  at android.media.MediaCodec.configure(MediaCodec.java:581)
                  at org.linphone.core.LinphoneCoreImpl.acceptCallWithParams(Native Method)
                  at org.linphone.core.LinphoneCoreImpl.acceptCallWithParams(LinphoneCoreImpl.java:975)
                  at org.linphone.LinphoneManager.acceptCallWithParams(LinphoneManager.java:1691)
                  at org.linphone.CallIncomingActivity.answer(CallIncomingActivity.java:304)
                  at org.linphone.CallIncomingActivity.access$700(CallIncomingActivity.java:48)
                  at org.linphone.CallIncomingActivity$2.onTouch(CallIncomingActivity.java:133)
                  at android.view.View.dispatchTouchEvent(View.java:8465)
                  at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
                  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
                  at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
                  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
                  at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
                  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
                  at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
                  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
                  at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
                  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
                  at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2369)
                  at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1719)
                  at android.app.Activity.dispatchTouchEvent(Activity.java:2757)`

Thanks for any advice. +_=

**Comment by arvinxian** [comment]
@douya40 the email has already sent

**Comment by arvinxian** [comment]
nope, this issue still here.

**Comment by Viish** [comment]
This should work with latest version on master branch.
