### ISSUE TITLE
Building Linphone on Ubuntu 18.04 LTS x64 with Android Studio

### ISSUE THREAD

**Issue by AhmadKhattak** [BelledonneCommunications/linphone-android#304]
Hi All,

Followed the steps in Readme and ran the ./prepare.py script and make.

After that with Android Studio, Imported the Project.

Now, Encountering the following error when building in Android Studio:

```

org.gradle.initialization.ReportedException: org.gradle.internal.exceptions.LocationAwareException: path may not be null or empty string. path=''
	at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:145)
	at org.gradle.initialization.DefaultGradleLauncher.executeTasks(DefaultGradleLauncher.java:115)
	at org.gradle.internal.invocation.GradleBuildController$1.call(GradleBuildController.java:78)
	at org.gradle.internal.invocation.GradleBuildController$1.call(GradleBuildController.java:75)
	at ....

```
Can anyone guide me on what is the reason for this error and how tor resolve it ?

Also, when running make install the following error is encountered,

```
> Configure project :liblinphone-sdk
WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation'.
It will be removed at the end of 2018
native sdk not ready yet

> Task :liblinphone-sdk:copyAssets FAILED

FAILURE: Build failed with an exception.

* What went wrong:
path may not be null or empty string. path=''

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

```

**Comment by deepbhavsar** [comment]
I am using Android studio 3.1.3 and facing same error.

what is wrong in it?

**Comment by sereja93** [comment]
error in `copyAssets` task  `liblinphone-sdk` module

**Comment by deepbhavsar** [comment]
@sereja93 

I set variable by

```
export ANDROID_HOME=$HOME/deep/android-sdk
export PATH=$PATH:$ANDROID_HOME/tools
export PATH=$PATH:$ANDROID_HOME/platform-tools

export ANDROID_HOME=$HOME/android-ndk-r17b
```

I follow all steps of git

still I am facing error:
Cause: path may not be null or empty string. path=''

**Comment by JimmyChen1984** [comment]
Hi @AhmadKhattak @deepbhavsar @sereja93 ,
I have the same error in copyAssets, do you know how to fix it?

**Comment by Viish** [comment]
Please see my answer in https://github.com/BelledonneCommunications/linphone-android/issues/321
