### ISSUE TITLE
Exception thrown in StatusFragment in onNotifyReceived

### ISSUE THREAD

**Issue by a1batross** [BelledonneCommunications/linphone-android#309]
Hi there.

I am not familiar with SIP, but seems code in onNotifyReceived is wrong.
Server sends a header with ```Voice-Message: 7/0 (0/0)```
Meanwhile code in onNotifyReceived tries to split by "voice-message". String.split() method does not care about case-insensitivity, so it fails with following backtrace:

```
07-09 17:28:21.729   899   899 W System.err: java.lang.ArrayIndexOutOfBoundsException: length=1; index=1
07-09 17:28:21.730   899   899 W System.err:    at org.linphone.fragments.StatusFragment$1.onNotifyReceived(StatusFragment.java:125)
07-09 17:28:21.730   899   899 W System.err:    at org.linphone.core.CoreImpl.iterate(Native Method)
07-09 17:28:21.730   899   899 W System.err:    at org.linphone.core.CoreImpl.iterate(Core.java:4591)
07-09 17:28:21.730   899   899 W System.err:    at org.linphone.LinphoneManager$2$1.run(LinphoneManager.java:647)
07-09 17:28:21.731   899   899 W System.err:    at android.os.Handler.handleCallback(Handler.java:751)
07-09 17:28:21.731   899   899 W System.err:    at android.os.Handler.dispatchMessage(Handler.java:95)
07-09 17:28:21.731   899   899 W System.err:    at android.os.Looper.loop(Looper.java:154)
07-09 17:28:21.731   899   899 W System.err:    at android.app.ActivityThread.main(ActivityThread.java:6121)
07-09 17:28:21.731   899   899 W System.err:    at java.lang.reflect.Method.invoke(Native Method)
07-09 17:28:21.731   899   899 W System.err:    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:898)
07-09 17:28:21.731   899   899 W System.err:    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:788)
```

Then I have fixed it, but it tries to pass an Integer to setText method. Android's setText(int) method means that this is internal resource(like R.string.some_localized_string), so it fails again.

```
07-09 17:57:26.968  2122  2122 W System.err: android.content.res.Resources$NotFoundException: String resource ID #0x7
07-09 17:57:26.969  2122  2122 W System.err:    at android.content.res.Resources.getText(Resources.java:335)
07-09 17:57:26.969  2122  2122 W System.err:    at android.widget.TextView.setText(TextView.java:4555)
07-09 17:57:26.969  2122  2122 W System.err:    at org.linphone.fragments.StatusFragment$1.onNotifyReceived(StatusFragment.java:129)
07-09 17:57:26.969  2122  2122 W System.err:    at org.linphone.core.CoreImpl.iterate(Native Method)
07-09 17:57:26.969  2122  2122 W System.err:    at org.linphone.core.CoreImpl.iterate(Core.java:4591)
07-09 17:57:26.969  2122  2122 W System.err:    at org.linphone.LinphoneManager$2$1.run(LinphoneManager.java:647)
07-09 17:57:26.969  2122  2122 W System.err:    at android.os.Handler.handleCallback(Handler.java:751)
07-09 17:57:26.969  2122  2122 W System.err:    at android.os.Handler.dispatchMessage(Handler.java:95)
07-09 17:57:26.969  2122  2122 W System.err:    at android.os.Looper.loop(Looper.java:154)
07-09 17:57:26.969  2122  2122 W System.err:    at android.app.ActivityThread.main(ActivityThread.java:6121)
07-09 17:57:26.969  2122  2122 W System.err:    at java.lang.reflect.Method.invoke(Native Method)
07-09 17:57:26.969  2122  2122 W System.err:    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:898)
07-09 17:57:26.969  2122  2122 W System.err:    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:788)
```

**Comment by Viish** [comment]
Thanks for the report, I'll fix that for the next release (4.1)
