### ISSUE TITLE
Whenever attempting call in background/Dead app linphone Manager crashes?

### ISSUE THREAD

**Issue by Harshjain2094** [BelledonneCommunications/linphone-android#331]
Getting this error when trying calling in the background.

```
Fatal Exception: java.lang.RuntimeException: Linphone Manager was already destroyed. Better use getLcIfManagerNotDestroyedOrNull and check returned value
       at com.bodaciousithub.rishtaapp.LinphoneCall.LinphoneManager.getInstance(LinphoneManager.java:481)
       at com.bodaciousithub.rishtaapp.LinphoneCall.LinphoneManager.getLc(LinphoneManager.java:489)
       at com.bodaciousithub.rishtaapp.helper.MyApplication.saveCreatedAccount(MyApplication.java:557)
       at com.bodaciousithub.rishtaapp.helper.MyApplication.startRegistration(MyApplication.java:535)
       at com.bodaciousithub.rishtaapp.helper.MyApplication.access$200(MyApplication.java:81)
       at com.bodaciousithub.rishtaapp.helper.MyApplication$2.run(MyApplication.java:527)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:145)
       at android.app.ActivityThread.main(ActivityThread.java:5938)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1400)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1195)
```

**Comment by gopipeddisetti** [comment]
Hello Team,

I am also getting the same issue ,when the app put background for long time .is there any solution for this.???

**Comment by Viish** [comment]
Yes, check if Service and/or Manager is alive before using it, and if it has been killed, start it again.
