### ISSUE TITLE
App Crash when Foreground start for Android 8+

### ISSUE THREAD

**Issue by daniel-ImpacTech** [BelledonneCommunications/linphone-android#351]
I've get latest source and when App start Foreground on Android 8+ the app Crash

Linphone Manager is already initialized

**Here is the Log:**

```
08-31 17:31:44.167 1395-1395/com.linphone/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.linphone, PID: 1395
    java.lang.RuntimeException: Unable to start service org.linphone.LinphoneService@a1c7a79 with Intent { act=android.intent.action.MAIN cmp=com.linphone/org.linphone.LinphoneService }: java.lang.RuntimeException: Linphone Manager is already initialized
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3721)
        at android.app.ActivityThread.-wrap20(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1793)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6798)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
     Caused by: java.lang.RuntimeException: Linphone Manager is already initialized
        at org.linphone.LinphoneManager.createAndStart(LinphoneManager.java:335)
        at org.linphone.LinphoneService.onStartCommand(LinphoneService.java:317)
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3704)
        at android.app.ActivityThread.-wrap20(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1793) 
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6798) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767) 
```

**Comment by clampx** [comment]
I am facing this too

**Comment by asafron** [comment]
Same here.
I think it happens after I add / remove contact from my native contact list and then trying to go back to Linphone (it was opened in background). Not sure it happens 100% of the time, but currently it seems related.

**Comment by asafron** [comment]
Any updates on that? Did you manage to workaround that or to get a reproducible scenario?

**Comment by Viish** [comment]
This has been fixed in master branch for a while now.
