### ISSUE TITLE
Deadlock in linphone android wrapper

### ISSUE THREAD

**Issue by f-lolom** [BelledonneCommunications/linphone-android#377]
Hello,

we are using linphone in our android application. We recently bumped the linphone version that we use to the 4.0.1 and since this upgrade, we started to have a lot of "Application Not Responding" (ANR) dialogs.
We found out that this was caused by a deadlock in the linphone android wrapper. Here is the following trace :

```
"main" prio=5 tid=1 Blocked
  | group="main" sCount=1 dsCount=0 flags=1 obj=0x73f91978 self=0xee559000
  | sysTid=4895 nice=0 cgrp=default sched=0/0 handle=0xf2ecf514
  | state=S schedstat=( 8075382299 2454362802 51422 ) utm=710 stm=97 core=1 HZ=100
  | stack=0xff22d000-0xff22f000 stackSize=8MB
  | held mutexes=
  at org.linphone.core.CallImpl.getDir(Call.java:-1)
  - waiting to lock <0x00295c97> (a org.linphone.core.CallImpl) held by thread 50
  at myapp.app.phone_call.GlobalCallStateListener.callStateChanged(GlobalCallStateListener.kt:18)
  at org.linphone.LinphoneService$1.onCallStateChanged(LinphoneService.java:456)
  at org.linphone.core.CoreImpl.iterate(Native method)
  at org.linphone.core.CoreImpl.iterate(Core.java:4591)
  - locked <0x0568fc55> (a org.linphone.core.CoreImpl)
  at org.linphone.LinphoneManager$2$1.run(LinphoneManager.java:653)
  at android.os.Handler.handleCallback(Handler.java:790)
  at android.os.Handler.dispatchMessage(Handler.java:99)
  at android.os.Looper.loop(Looper.java:164)
  at android.app.ActivityThread.main(ActivityThread.java:6494)
  at java.lang.reflect.Method.invoke(Native method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

// ....

  "RxCachedThreadScheduler-9" daemon prio=5 tid=50 Blocked
  | group="main" sCount=1 dsCount=0 flags=1 obj=0x131c49b0 self=0xc6ba4600
  | sysTid=5282 nice=0 cgrp=default sched=0/0 handle=0xcc675970
  | state=S schedstat=( 17790495 23292146 51 ) utm=1 stm=0 core=1 HZ=100
  | stack=0xcc573000-0xcc575000 stackSize=1038KB
  | held mutexes=
  at org.linphone.core.CallImpl.getDuration(Call.java:808)
  - waiting to lock <0x0568fc55> (a org.linphone.core.CoreImpl) held by thread 1
  - locked <0x00295c97> (a org.linphone.core.CallImpl)
  at myapp.data.PhoneRepository.getLinphoneCallBaseTimer(PhoneRepository.kt:383)
  at myapp.data.PhoneRepository.getCallBaseTimer(PhoneRepository.kt:373)
...
  at java.lang.Thread.run(Thread.java:764)
```

We have a deadlock on two CallImpl/CoreImpl instances: 
In the main thread, the "iterate" method of linphone holds a lock on the "Core" object, do its job, and then triggers all the listeners : this reach our code that use the "Call" object
In an other thread, we use "Call#getDuration", which hold a lock on the Call object and internally requires a lock on the Core object -> This lead to a deadlock

We will try to fix this issue on our side by making sure that we only use the linphone api on the main thread, but it doesn't look like a viable solution in the long term, especially if linphone is meant to be thread safe : we don't want to perform heavy operations, like fetching the call history in the main thread.

Can you have a look at this is ?

**Comment by Viish** [comment]
Currently liblinphone isn't thread safe and should always be used from the same thread, preferably UI.
