### ISSUE TITLE
Error during runtime : android.support.v7.widget.RecyclerView cannot be cast to android.widget.ListView

### ISSUE THREAD

**Issue by mehran22k** [BelledonneCommunications/linphone-android#397]
Hi guys
i need help

first i clone the master branch

while make i have this Error:  error: cannot find symbol variable mChatRoomSecurityLevel

i search and find a solution:  replace SRC folder of  4.0.1 version with my master SRC folder in my project : [#384](https://github.com/BelledonneCommunications/linphone-android/issues/384)

then i make the project successfully and try to test it by real Device (Android 6)
now app work correctly but when i want  to goto some Activities the app crashed. i debug it and see this error:

inputType=0x21, imeOptions=0x4006, privateImeOptions=null }, windowGainingFocus=android.view.ViewRootImpl$W@b7faec4, mServedView=org.linphone.ui.AddressText{306a17 VFED..CL. .F....I. 0,0-900,180 #7f09003f app:id/address}, mServedInputConnectionWrapper=android.view.inputmethod.InputMethodManager$ControlledInputConnectionWrapper@c3551ad
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: org.linphone, PID: 4588
                  **java.lang.ClassCastException: android.support.v7.widget.RecyclerView cannot be cast to android.widget.ListView
                      at org.linphone.contacts.ContactsListFragment.onCreateView(ContactsListFragment.java:90)
                      at android.app.Fragment.performCreateView(Fragment.java:2238)
                      at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:977)
                      at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1152)
                      at android.app.BackStackRecord.run(BackStackRecord.java:793)
                      at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1539)
                      at android.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:566)
                      at org.linphone.activities.LinphoneActivity.changeFragment(LinphoneActivity.java:497)
                      at org.linphone.activities.LinphoneActivity.changeCurrentFragment(LinphoneActivity.java:460)
                      at org.linphone.activities.LinphoneActivity.changeCurrentFragment(LinphoneActivity.java:370)
                      at org.linphone.activities.LinphoneActivity.onClick(LinphoneActivity.java:840)
                      at android.view.View.performClick(View.java:5232)
                      at android.view.View$PerformClick.run(View.java:21289)
                      at android.os.Handler.handleCallback(Handler.java:739)
                      at android.os.Handler.dispatchMessage(Handler.java:95)
                      at android.os.Looper.loop(Looper.java:168)
                      at android.app.ActivityThread.main(ActivityThread.java:5885)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:797)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:687)**

![2](https://user-images.githubusercontent.com/2356522/48201865-9d556480-e378-11e8-9690-ee80d3a412ca.JPG)

what should id do?

please help me 
thank you...

**Comment by mehran22k** [comment]
Thanks @Viish  


the problem solved in latest commit by Viish

**Comment by d41z** [comment]
@mehran22k 
what was the error?. I have a similar problem and I'm trying to fix it

**Comment by mehran22k** [comment]
@d41z
just clone the latest version, its solved
