### ISSUE TITLE
Crash After changing package name

### ISSUE THREAD

**Issue by mehran22k** [BelledonneCommunications/linphone-android#409]
Hi guys
after successful build i try to make with different package name so i do these:

**look for the function named "getPackageName()" and change it value accordingly
also update the values in the AndroidManifest file where the comment appears
change the package name also in the files: res/xml/syncadapter.xml, res/xml/contacts.xml and res/values/non_localizable_custom where appears
run again the Makefile script by calling "make"**

so i call make but it show some error about **R file not resolved**  and build failed

then i open project in android studio, clean and rebuild it , but still fail to compile and show Error that  **R file not resolved** 

then, in android studio by right click on linphone under org==>  refactor ==>  rename , try to rename package and refactor...
now project build successfully but when i install it and try to run the app crashed , here is my log:

(i just want to change the package name from org.linphone to org.voipapp)

**11-24 22:06:50.752 5112-5112/org.voipapp E/art: No implementation found for boolean org.voipapp .mediastream.Version.nativeHasNeon() (tried Java_org_voipapp_mediastream_Version_nativeHasNeon and Java_org_voipapp_mediastream_Version_nativeHasNeon__)**

 at org.voipapp.mediastream.Version.nativeHasNeon(Native Method)
        at org.voipapp.mediastream.Version.hasNeon(Version.java:134)
        at org.voipapp.mediastream.Version.dumpCapabilities(Version.java:161)
        at org.voipapp.core.FactoryImpl.<clinit>(Factory.java:269)
        at org.voipapp.core.Factory.instance(Factory.java:37)
        at org.voipapp.LinphoneService.onCreate(LinphoneService.java:456)
        at android.app.ActivityThread.handleCreateService(ActivityThread.java:2780)
        at android.app.ActivityThread.access$1800(ActivityThread.java:153)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1388)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5298)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)

**Please help me 
thanks**

**Comment by Viish** [comment]
You musn't change the package name of the java code in the sources.
If you follow correctly the instructions in the README file it should work just fine.
You can also try to use the feature/release-4.1 branch (under development) which have an easier way of changing package name (see README).

**Comment by mehran22k** [comment]
Hi 
Thanks a lot @Viish
I Download the zipped of release-4.1 then i open in android studio but i have some error while build
may you please help me . thanks

**Could not find org.linphone:liblinphone-sdk:4.1-DEBUG.**

![untitled](https://user-images.githubusercontent.com/2356522/49008637-8b026580-f183-11e8-87d9-d5fd89f7f229.png)

i check maven repository but there is no 4.1 folder

**Comment by Viish** [comment]
Hi @mehran22k,
Yes currently this branch cannot use a remote aar because it's not ready (and not published obviously).
You have to build a local aar (see the README).
If you prefer, fork the linphone-android master branch and apply changes for package name simplifications that are in the feature/release-4.1 branch to it.
