### ISSUE TITLE
App version 4.0.1: crash when setting up SIP account

### ISSUE THREAD

**Issue by voltagex** [BelledonneCommunications/linphone-android#456]
```
FATAL EXCEPTION: main
Process: org.linphone, PID: 8791
java.lang.NullPointerException: Attempt to invoke interface method 'void org.linphone.core.Address.setDisplayName(java.lang.String)' on a null object reference
    at org.linphone.LinphonePreferences$AccountBuilder.saveNewAccount(LinphonePreferences.java:346)
    at org.linphone.assistant.AssistantActivity.saveCreatedAccount(AssistantActivity.java:559)
    at org.linphone.assistant.AssistantActivity.genericLogIn(AssistantActivity.java:432)
    at org.linphone.assistant.LoginFragment.onClick(LoginFragment.java:88)
    at android.view.View.performClick(View.java:6921)
    at android.widget.TextView.performClick(TextView.java:12738)
    at android.view.View$PerformClick.run(View.java:26197)
    at android.os.Handler.handleCallback(Handler.java:790)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:164)
    at android.app.ActivityThread.main(ActivityThread.java:7002)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)
```

This happens whether I enter a display name or not, so I'm not sure what's going on.

**Comment by Viish** [comment]
This means the address you created and on which you try to set your display name (or any other operation) hasn't been created due (most probably) to an invalid input.
How do you create it ?

**Comment by Viish** [comment]
That doesn't help very much. Which functions are you calling ? What information you give to it ?

**Comment by Viish** [comment]
Like I said, most probably an invalid input ;)

**Comment by voltagex** [comment]
Yes but it shouldn't *crash* the app. It should warn the user instead.

**Comment by Viish** [comment]
When you try to create an address with an invalid input, it will return null because it couldn't do it. That is up to the developer to check if the result is null before using the address and warn the user the input wasn't correct.

**Comment by voltagex** [comment]
This is in your Android app - is this the right place to report issues in
it?
