### ISSUE TITLE
Error while running ./prepare.py

### ISSUE THREAD

**Issue by arunkrishna2992** [BelledonneCommunications/linphone-android#463]
NDK version - android-ndk-r18b
Please see the logs

___________________________________________________________________________________

FAILURE: Build failed with an exception.

* What went wrong:
Could not create service of type ScriptPluginFactory using BuildScopeServices.createScriptPluginFactory().
 Could not create service of type CrossBuildFileHashCache using BuildSessionScopeServices.createCrossBuildFileHashCache().

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s
```
Traceback (most recent call last):
  File "./prepare.py", line 473, in <module>
    sys.exit(main())
  File "./prepare.py", line 470, in main
    return preparator.run()
  File "submodules/cmake-builder/prepare.py", line 505, in run
    return self.prepare()
  File "./prepare.py", line 210, in prepare
    prepare.Preparator.prepare(self)
  File "submodules/cmake-builder/prepare.py", line 473, in prepare
    ret = self.target_prepare(self.targets[target_name])
  File "submodules/cmake-builder/prepare.py", line 433, in target_prepare
    os.makedirs(target.abs_cmake_dir)
  File "/usr/lib/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/usr/lib/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/usr/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
```
OSError: [Errno 13] Permission denied: '/home/arun/Downloads/linphone-android/WORK'

___________________________________________________________________________________

**Comment by Viish** [comment]
Check your gradle version (your issue isn't related to us) or use the feature/release-4.1 branch.
