### ISSUE TITLE
Crash on video init

### ISSUE THREAD

**Issue by licaon-kter** [BelledonneCommunications/linphone-android#477]
AOSP 9, 4.0.1 F-Droid (not seeing this with the app from the website)

When calling another Linphone app, if either side, caller or callee, has "Initiate video calls" toggled on, when they call each other the app on the Android 9 device will crash. 

But the app on the Android 6 device will not.

If the other side has a different SIP app, say [baresip](https://github.com/juha-h/baresip-studio), it will not crash and video will start (black screen as baresip can't do video, small preview from my camera).

Logcat:
```
02-16 23:36:01.917 D/AndroidRuntime(11701): Shutting down VM
02-16 23:36:01.918 E/AndroidRuntime(11701): FATAL EXCEPTION: main
02-16 23:36:01.918 E/AndroidRuntime(11701): Process: org.linphone, PID: 11701
02-16 23:36:01.918 E/AndroidRuntime(11701): java.lang.RuntimeException: Unable to start activity ComponentInfo{org.linphone/org.linphone.activities.LinphoneActivity}: java.lang.RuntimeException: Linphone Manager should be created before accessed
02-16 23:36:01.918 E/AndroidRuntime(11701): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2951)
02-16 23:36:01.918 E/AndroidRuntime(11701): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3086)
02-16 23:36:01.918 E/AndroidRuntime(11701): 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
02-16 23:36:01.918 E/AndroidRuntime(11701): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
02-16 23:36:01.918 E/AndroidRuntime(11701): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
02-16 23:36:01.918 E/AndroidRuntime(11701): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1816)
02-16 23:36:01.918 E/AndroidRuntime(11701): 	at android.os.Handler.dispatchMessage(Handler.java:106)
02-16 23:36:01.918 E/AndroidRuntime(11701): 	at android.os.Looper.loop(Looper.java:193)
02-16 23:36:01.918 E/AndroidRuntime(11701): 	at android.app.ActivityThread.main(ActivityThread.java:6718)
02-16 23:36:01.918 E/AndroidRuntime(11701): 	at java.lang.reflect.Method.invoke(Native Method)
02-16 23:36:01.918 E/AndroidRuntime(11701): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
02-16 23:36:01.918 E/AndroidRuntime(11701): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
02-16 23:36:01.918 E/AndroidRuntime(11701): Caused by: java.lang.RuntimeException: Linphone Manager should be created before accessed
02-16 23:36:01.918 E/AndroidRuntime(11701): 	at org.linphone.LinphoneManager.getInstance(LinphoneManager.java:412)
02-16 23:36:01.918 E/AndroidRuntime(11701): 	at org.linphone.LinphoneManager.getLc(LinphoneManager.java:416)
02-16 23:36:01.918 E/AndroidRuntime(11701): 	at org.linphone.chat.GroupChatFragment.onCreateView(GroupChatFragment.java:116)
02-16 23:36:01.918 E/AndroidRuntime(11701): 	at android.app.Fragment.performCreateView(Fragment.java:2522)
02-16 23:36:01.918 E/AndroidRuntime(11701): 	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1298)
02-16 23:36:01.918 E/AndroidRuntime(11701): 	at android.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1576)
02-16 23:36:01.918 E/AndroidRuntime(11701): 	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1637)
02-16 23:36:01.918 E/AndroidRuntime(11701): 	at android.app.FragmentManagerImpl.dispatchMoveToState(FragmentManager.java:3046)
02-16 23:36:01.918 E/AndroidRuntime(11701): 	at android.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:2998)
02-16 23:36:01.918 E/AndroidRuntime(11701): 	at android.app.FragmentController.dispatchActivityCreated(FragmentController.java:182)
02-16 23:36:01.918 E/AndroidRuntime(11701): 	at android.app.Activity.performCreate(Activity.java:7151)
3:36:01.918 E/AndroidRuntime(11701): 	at android.app.Activity.performCreate(Activity.java:7135)
02-16 23:36:01.918 E/AndroidRuntime(11701): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1272)
02-16 23:36:01.918 E/AndroidRuntime(11701): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2931)
02-16 23:36:01.918 E/AndroidRuntime(11701): 	... 11 more
```

**Comment by Viish** [comment]
Same issue and same solution as for #478
