### ISSUE TITLE
Leaked IntentReceiver Doze Receiver

### ISSUE THREAD

**Issue by SarunyuPrasert** [BelledonneCommunications/linphone-android#479]
Following to this issue #462 I clone a project from master branch not feature/release-4.1 branch but the problem still occur and it make my application crash when start

E/ActivityThread: Activity th.co.entronica.sipuademo.LauncherActivity has leaked IntentReceiver org.linphone.core.tools.DozeReceiver@67c1d0f that was originally registered here. Are you missing a call to unregisterReceiver()?
    android.app.IntentReceiverLeaked: Activity th.co.entronica.sipuademo.LauncherActivity has leaked IntentReceiver org.linphone.core.tools.DozeReceiver@67c1d0f that was originally registered here. Are you missing a call to unregisterReceiver()?
        at android.app.LoadedApk$ReceiverDispatcher.<init>(LoadedApk.java:928)
        at android.app.LoadedApk.getReceiverDispatcher(LoadedApk.java:729)
        at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1174)
        at android.app.ContextImpl.registerReceiver(ContextImpl.java:1154)
        at android.app.ContextImpl.registerReceiver(ContextImpl.java:1148)
        at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:554)
        at org.linphone.core.tools.AndroidPlatformHelper.onLinphoneCoreReady(AndroidPlatformHelper.java:160)
        at org.linphone.core.CoreImpl.start(Native Method)
        at org.linphone.core.CoreImpl.start(Core.java:4976)
        at th.co.ais.mino.sdk.api.sip.SipUAManager.startLibLinphone(SipUAManager.java:264)
        at th.co.ais.mino.sdk.api.sip.SipUAManager.createAndStart(SipUAManager.java:236)
        at th.co.ais.mino.sdk.api.sip.SipUAManager.initSipUAManager(SipUAManager.java:184)
        at th.co.entronica.sipuademo.LauncherActivity.prepareAndStartLibrary(LauncherActivity.java:288)
        at th.co.entronica.sipuademo.LauncherActivity.onCreate(LauncherActivity.java:93)
        at android.app.Activity.performCreate(Activity.java:6351)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1114)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2470)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2577)
        at android.app.ActivityThread.access$1000(ActivityThread.java:166)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1414)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5619)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:853)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:737)

**Comment by Viish** [comment]
Yes on master branch this is expected, because linphone's submodule revision is f83d6c4a79c085ef75310bf5582bb28ce76fa2ff and the fix is in revision 46d2412fd3fd07e99304eb11ff4d2b6c4c01bd25.
Build an up-to-date SDK to fix this issue.

**Comment by SarunyuPrasert** [comment]
So, Do I have to switch to release/4.0.1 branch to solve this?

**Comment by Viish** [comment]
Yes release/4.0.1 shouldn't have this issue.

**Comment by marksaitis** [comment]
> Yes release/4.0.1 shouldn't have this issue.

Do we know where was the fix?
