### ISSUE TITLE
4.1 crash without CONTACTS permissions

### ISSUE THREAD

**Issue by licaon-kter** [BelledonneCommunications/linphone-android#481]
```
W ActivityManager: Permission Denial: opening provider com.android.providers.contacts.ContactsProvider2 from ProcessRecord{1781487 7595:org.linphone/u0a448} (pid=7595, uid=10448) requires android.permission.READ_CONTACTS or android.permission.WRITE_CONTACTS
D AndroidRuntime: Shutting down VM
E AndroidRuntime: FATAL EXCEPTION: main
E AndroidRuntime: Process: org.linphone, PID: 7595
E AndroidRuntime: java.lang.SecurityException: Permission Denial: opening provider com.android.providers.contacts.ContactsProvider2 from ProcessRecord{1781487 7595:org.linphone/u0a448} (pid=7595, uid=10448) requires android.permission.READ_CONTACTS or android.permission.WRITE_CONTACTS
E AndroidRuntime:        at android.os.Parcel.createException(Parcel.java:1950)
E AndroidRuntime:        at android.os.Parcel.readException(Parcel.java:1918)
E AndroidRuntime:        at android.os.Parcel.readException(Parcel.java:1868)
E AndroidRuntime:        at android.app.IActivityManager$Stub$Proxy.getContentProvider(IActivityManager.java:4185)
E AndroidRuntime:        at android.app.ActivityThread.acquireProvider(ActivityThread.java:6019)
E AndroidRuntime:        at android.app.ContextImpl$ApplicationContentResolver.acquireProvider(ContextImpl.java:2573)
E AndroidRuntime:        at android.content.ContentResolver.acquireProvider(ContentResolver.java:1784)
E AndroidRuntime:        at android.content.ContentResolver.acquireContentProviderClient(ContentResolver.java:1859)
E AndroidRuntime:        at org.linphone.c.i.l(ContactsManager.java:275)
E AndroidRuntime:        at org.linphone.c.i.m(ContactsManager.java:325)
E AndroidRuntime:        at org.linphone.c.i.a(ContactsManager.java:260)
E AndroidRuntime:        at org.linphone.LinphoneActivity.onStart(LinphoneActivity.java:1393)
E AndroidRuntime:        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1392)
E AndroidRuntime:        at android.app.Activity.performStart(Activity.java:7165)
E AndroidRuntime:        at android.app.ActivityThread.handleStartActivity(ActivityThread.java:2975)
E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:180)
E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:165)
E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:142)
E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1816)
E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
E AndroidRuntime:        at android.os.Looper.loop(Looper.java:193)
E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6718)
E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
E AndroidRuntime: Caused by: android.os.RemoteException: Remote stack trace:
E AndroidRuntime:        at com.android.server.am.ActivityManagerService.getContentProviderImpl(ActivityManagerService.java:12255)
E AndroidRuntime:        at com.android.server.am.ActivityManagerService.getContentProvider(ActivityManagerService.java:12662)
E AndroidRuntime:        at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:358)
E AndroidRuntime:        at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3307)
E AndroidRuntime:        at android.os.Binder.execTransact(Binder.java:731)
E AndroidRuntime:
```

AOSP 9, 4.1 HEAD @ https://github.com/BelledonneCommunications/linphone-android/commit/f110e817d54838d733cf75d05bec3b1f9566a49d

**Comment by Viish** [comment]
Thanks for the report, I just fixed it.

commit 9e076971a054526fe8d9a459a738cb58c0af6b70 (HEAD -> feature/release-4.1, origin/feature/release-4.1)
Author: Sylvain Berfini <sylvain.berfini@belledonne-communications.com>
Date:   Fri Feb 22 10:27:20 2019 +0100
    Fixed crash if contact permission isn't granted + auto fetch if granted while in contacts fragment
