### ISSUE TITLE
Video call not ending

### ISSUE THREAD

**Issue by Miteshmakwana73** [BelledonneCommunications/linphone-android#515]
I am facing problem whenever I try to call it's automatically start a video call and it's not going back to audio on pressing of video button,
I am getting this on the click of video
```
2019-03-22 17:25:39.297 17100-17100/org.linphone I/Jenya Sip Call: [Permission] Camera permission is granted
2019-03-22 17:25:39.298 17100-17100/org.linphone I/Jenya Sip Call: Call 0xe37ee000: moving from state LinphoneCallStreamsRunning to LinphoneCallUpdating
2019-03-22 17:25:39.298 17100-17100/org.linphone I/Jenya Sip Call: New call state [Updating]
2019-03-22 17:25:39.305 17100-17100/org.linphone I/Jenya Sip Call: Call 0xe37ee000 is locking sound resources.
2019-03-22 17:25:39.305 17100-17100/org.linphone I/Jenya Sip Call: Call 0xe37ee000 is locking sound resources.
2019-03-22 17:25:39.305 17100-17100/org.linphone I/Jenya Sip Call: Linphone core [0xf1850400] notifying [call_state_changed]
2019-03-22 17:25:39.307 17100-17100/org.linphone I/Jenya Sip Call: Don't put video stream on local offer for call [0xe37ee000]
2019-03-22 17:25:39.308 17100-17100/org.linphone I/Jenya Sip Call: Don't put text stream on local offer for call [0xe37ee000]
2019-03-22 17:25:39.308 17100-17100/org.linphone I/Jenya Sip Call: Modifying call parameters...
2019-03-22 17:25:39.308 17100-17100/org.linphone I/Jenya Sip Call: Linphone core [0xf1850400] notifying [display_status]
2019-03-22 17:25:39.309 17100-17100/org.linphone I/Jenya Sip Call: Dialog [0xe9f7c680]: now updated by transaction [0xd3e64360].
2019-03-22 17:25:39.309 17100-17100/org.linphone I/Jenya Sip Call: Changing [client] [INVITE] transaction [0xd3e64360], from state [INIT] to [CALLING]
2019-03-22 17:25:39.310 17100-17100/org.linphone I/Jenya Sip Call: channel [0xe9dd52c0]: message sent to [UDP://mydomain:8086], size: [1506] bytes
2019-03-22 17:25:39.310 17100-17100/org.linphone I/Jenya Sip Call: INVITE sip:mod_sofia@104.237.141.82:5060 SIP/2.0
2019-03-22 17:25:39.310 17100-17100/org.linphone I/Jenya Sip Call: Via: SIP/2.0/UDP 192.168.0.101:5060;branch=z9hG4bK.Xw6xm-YBM;rport
2019-03-22 17:25:39.310 17100-17100/org.linphone I/Jenya Sip Call: From: <sip:989865651212@xxx.xxx.xx.xx;app-id=622464153529;pn-type=google;pn-tok=APA91bF25H3jzU15geM881P3-uHuK6rIq16g4MzD_TfUooLBk9xa7VzeHrr7XS9bL0rWmUSqJwZkpJqJ34L-JJc0wdZiMdwuxijXJ61W_U3UeRM-PZZUVnM>;tag=w4SmFOf
2019-03-22 17:25:39.310 17100-17100/org.linphone I/Jenya Sip Call: To: "123456" <sip:123456@mydomain:8086>;tag=evc4SZ4ma69ee
2019-03-22 17:25:39.310 17100-17100/org.linphone I/Jenya Sip Call: CSeq: 113 INVITE
2019-03-22 17:25:39.310 17100-17100/org.linphone I/Jenya Sip Call: Call-ID: 284cca94-c73c-1237-f09d-12db2fa4fcd8
2019-03-22 17:25:39.310 17100-17100/org.linphone I/Jenya Sip Call: Max-Forwards: 70
2019-03-22 17:25:39.310 17100-17100/org.linphone I/Jenya Sip Call: Subject: Media change
2019-03-22 17:25:39.310 17100-17100/org.linphone I/Jenya Sip Call: Allow: INVITE, ACK, CANCEL, OPTIONS, BYE, REFER, NOTIFY, MESSAGE, SUBSCRIBE, INFO, UPDATE
2019-03-22 17:25:39.310 17100-17100/org.linphone I/Jenya Sip Call: Content-Type: application/sdp
2019-03-22 17:25:39.310 17100-17100/org.linphone I/Jenya Sip Call: Content-Length: 522
2019-03-22 17:25:39.310 17100-17100/org.linphone I/Jenya Sip Call: Contact: <sip:989865651212@xxx.xxx.xx.xx;app-id=622464153529;pn-type=google;pn-tok=APA91bF25H3jzU15geM881P3-uHuK6rIq16g4MzD_TfUooLBk9xa7VzeHrr7XS9bL0rWmUSqJwZkpJqJ34L-JJc0wdZiMdwuxijXJ61W_U3UeRM-PZZUVnM;transport=udp>;+sip.instance="<urn:uuid:7a09d0a7-8e41-4ec6-8b8b-871569b0ca98>"
2019-03-22 17:25:39.310 17100-17100/org.linphone I/Jenya Sip Call: User-Agent: LinphoneAndroid/1.0 (belle-sip/1.4.2)
2019-03-22 17:25:39.310 17100-17100/org.linphone I/Jenya Sip Call: v=0
2019-03-22 17:25:39.310 17100-17100/org.linphone I/Jenya Sip Call: o=989865651212 2887 2213 IN IP4 192.168.0.101
2019-03-22 17:25:39.310 17100-17100/org.linphone I/Jenya Sip Call: s=Talk
2019-03-22 17:25:39.310 17100-17100/org.linphone I/Jenya Sip Call: c=IN IP4 192.168.0.101
2019-03-22 17:25:39.310 17100-17100/org.linphone I/Jenya Sip Call: b=AS:380
2019-03-22 17:25:39.310 17100-17100/org.linphone I/Jenya Sip Call: t=0 0
2019-03-22 17:25:39.310 17100-17100/org.linphone I/Jenya Sip Call: a=rtcp-xr:rcvr-rtt=all:10000 stat-summary=loss,dup,jitt,TTL voip-metrics
2019-03-22 17:25:39.310 17100-17100/org.linphone I/Jenya Sip Call: m=audio 7076 RTP/AVP 96 97 98 99 0 8 101 100 102
2019-03-22 17:25:39.310 17100-17100/org.linphone I/Jenya Sip Call: a=rtpmap:96 opus/48000/2
2019-03-22 17:25:39.310 17100-17100/org.linphone I/Jenya Sip Call: a=fmtp:96 useinbandfec=1
2019-03-22 17:25:39.310 17100-17100/org.linphone I/Jenya Sip Call: a=rtpmap:97 SILK/16000
2019-03-22 17:25:39.310 17100-17100/org.linphone I/Jenya Sip Call: a=rtpmap:98 speex/16000
2019-03-22 17:25:39.310 17100-17100/org.linphone I/Jenya Sip Call: a=fmtp:98 vbr=on
2019-03-22 17:25:39.310 17100-17100/org.linphone I/Jenya Sip Call: a=rtpmap:99 speex/8000
2019-03-22 17:25:39.310 17100-17100/org.linphone I/Jenya Sip Call: a=fmtp:99 vbr=on
2019-03-22 17:25:39.310 17100-17100/org.linphone I/Jenya Sip Call: a=rtpmap:101 telephone-event/48000
2019-03-22 17:25:39.310 17100-17100/org.linphone I/Jenya Sip Call: a=rtpmap:100 telephone-event/16000
2019-03-22 17:25:39.310 17100-17100/org.linphone I/Jenya Sip Call: a=rtpmap:102 telephone-event/8000
2019-03-22 17:25:39.310 17100-17100/org.linphone I/Jenya Sip Call: m=video 0 RTP/AVP 0
2019-03-22 17:25:39.310 17100-17100/org.linphone I/Jenya Sip Call: a=inactive
2019-03-22 17:25:39.395 17100-17100/org.linphone I/Jenya Sip Call: bellesip_wake_lock_acquire(): Android wake lock acquired [ref=0x1010a2]
2019-03-22 17:25:39.395 17100-17100/org.linphone I/Jenya Sip Call: channel [0xe9dd52c0]: starting recv background task with id=[1010a2].
2019-03-22 17:25:39.396 17100-17100/org.linphone I/Jenya Sip Call: channel [0xe9dd52c0]: received [1091] new bytes from [UDP://mydomain:8086]:
2019-03-22 17:25:39.396 17100-17100/org.linphone I/Jenya Sip Call: INFO sip:989865651212@XXX.XXX.XX.XXX:5060;app-id=622464153529;pn-type=google;pn-tok=APA91bF25H3jzU15geM881P3-uHuK6rIq16g4MzD_TfUooLBk9xa7VzeHrr7XS9bL0rWmUSqJwZkpJqJ34L-JJc0wdZiMdwuxijXJ61W_U3UeRM-PZZUVnM;transport=udp SIP/2.0
2019-03-22 17:25:39.396 17100-17100/org.linphone I/Jenya Sip Call: Via: SIP/2.0/UDP 104.237.141.82;rport;branch=z9hG4bKDm7Fyt4DXcNrK
2019-03-22 17:25:39.396 17100-17100/org.linphone I/Jenya Sip Call: Max-Forwards: 70
2019-03-22 17:25:39.396 17100-17100/org.linphone I/Jenya Sip Call: From: "123456" <sip:123456@mydomain:8086>;tag=evc4SZ4ma69ee
2019-03-22 17:25:39.396 17100-17100/org.linphone I/Jenya Sip Call: To: <sip:989865651212@192.168.1.245:5060;app-id=622464153529;pn-type=google;pn-tok=APA91bF25H3jzU15geM881P3-uHuK6rIq16g4MzD_TfUooLBk9xa7VzeHrr7XS9bL0rWmUSqJwZkpJqJ34L-JJc0wdZiMdwuxijXJ61W_U3UeRM-PZZUVnM;transport=udp>;tag=w4SmFOf
2019-03-22 17:25:39.396 17100-17100/org.linphone I/Jenya Sip Call: Call-ID: 284cca94-c73c-1237-f09d-12db2fa4fcd8
2019-03-22 17:25:39.396 17100-17100/org.linphone I/Jenya Sip Call: CSeq: 2074088 INFO
2019-03-22 17:25:39.396 17100-17100/org.linphone I/Jenya Sip Call: Contact: <sip:mod_sofia@104.237.141.82:5060>
2019-03-22 17:25:39.396 17100-17100/org.linphone I/Jenya Sip Call: User-Agent: SWITCH
2019-03-22 17:25:39.396 17100-17100/org.linphone I/Jenya Sip Call: Allow: INVITE, ACK, BYE, CANCEL, OPTIONS, MESSAGE, INFO, UPDATE, REGISTER, NOTIFY, PUBLISH, SUBSCRIBE
2019-03-22 17:25:39.396 17100-17100/org.linphone I/Jenya Sip Call: Supported: path, replaces
2019-03-22 17:25:39.396 17100-17100/org.linphone I/Jenya Sip Call: Content-Type: application/media_control+xml
2019-03-22 17:25:39.396 17100-17100/org.linphone I/Jenya Sip Call: Content-Length: 149
2019-03-22 17:25:39.396 17100-17100/org.linphone I/Jenya Sip Call: <?xml version="1.0" encoding="utf-8" ?>
```
and some times I am getting this error on video call after some time
```
2019-03-22 16:19:05.330 9176-9176/org.linphone E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.linphone, PID: 9176
    java.lang.RuntimeException: Unable to start receiver org.linphone.KeepAliveHandler: java.lang.NullPointerException: Attempt to invoke interface method 'boolean org.linphone.core.LpConfig.getBool(java.lang.String, java.lang.String, boolean)' on a null object reference
        at android.app.ActivityThread.handleReceiver(ActivityThread.java:3105)
        at android.app.ActivityThread.-wrap18(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1609)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:163)
        at android.app.ActivityThread.main(ActivityThread.java:6238)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)
     Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'boolean org.linphone.core.LpConfig.getBool(java.lang.String, java.lang.String, boolean)' on a null object reference
        at org.linphone.LinphonePreferences.isDebugEnabled(LinphonePreferences.java:1110)
        at org.linphone.KeepAliveHandler.onReceive(KeepAliveHandler.java:33)
        at android.app.ActivityThread.handleReceiver(ActivityThread.java:3098)
        at android.app.ActivityThread.-wrap18(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1609) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:163) 
        at android.app.ActivityThread.main(ActivityThread.java:6238) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794) 

```

**Comment by Viish** [comment]
You can remove the KeepAlive handler from your app, it is now handled by the library.
For the video, it seems the issue comes from your server that answers an INFO message to the INVITE.

**Comment by Miteshmakwana73** [comment]
after removing KeepAliveHandler.java I am getting this error

```
2019-03-23 11:53:08.558 25197-25197/org.linphone E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.linphone, PID: 25197
    java.lang.UnsatisfiedLinkError: No implementation found for void org.linphone.mediastream.Log.i(java.lang.String) (tried Java_org_linphone_mediastream_Log_i and Java_org_linphone_mediastream_Log_i__Ljava_lang_String_2)
        at org.linphone.mediastream.Log.i(Native Method)
        at org.linphone.mediastream.Log.i(Log.java:46)
        at org.linphone.CallOutgoingActivity.checkAndRequestCallPermissions(CallOutgoingActivity.java:282)
        at org.linphone.CallOutgoingActivity.onStart(CallOutgoingActivity.java:185)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1270)
        at android.app.Activity.performStart(Activity.java:6689)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2622)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2724)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1473)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6123)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
```

**Comment by Viish** [comment]
This has nothing to do with the keepalive. It looks like it rails to load our library.

**Comment by Miteshmakwana73** [comment]
hello @Viish ,
I am getting [this](https://i.imgur.com/yz23aASg.jpg) response from the server, what should I do now?

**Comment by Viish** [comment]
I can't read text in red in your image but the green flow looks OK as well as the invite message.

**Comment by Miteshmakwana73** [comment]
check [this](https://imgur.com/gallery/lfN19oV)

**Comment by Viish** [comment]
When you disable/enable video while in call, our library will send a new INVITE. But the problem seems to be the OPTION message sent by our server (or it doesn't use the new INVITE correctly).

**Comment by Miteshmakwana73** [comment]
is it possible to enable/disable video run time while call is active because if I uncheck video from setting it allow me to audio call

**Comment by Viish** [comment]
Yes it is, you can try with a sip.linphone.org account it works just as expected.

**Comment by Miteshmakwana73** [comment]
@Viish linphone automatically check  accept incoming video request check box after any call finish

**Comment by Miteshmakwana73** [comment]
@Viish did you find any solution?

**Comment by Viish** [comment]
As I said, I believe the problem to be in your server config.
