### ISSUE TITLE
Unable to start activity ComponentInfo{org.linphone.debug/org.linphone.LinphoneActivity}

### ISSUE THREAD

**Issue by brianjmurrell** [BelledonneCommunications/linphone-android#532]
On feature/release-4.1 on a Nexus 5 running LineageOS 15.1:

```
03-27 11:45:37.303 22934 22934 E AndroidRuntime: FATAL EXCEPTION: main
03-27 11:45:37.303 22934 22934 E AndroidRuntime: Process: org.linphone.debug, PID: 22934
03-27 11:45:37.303 22934 22934 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{org.linphone.debug/org.linphone.LinphoneActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'boolean org.linphone.core.Config.getBool(java.lang.String, java.lang.String, boolean)' on a null object reference
03-27 11:45:37.303 22934 22934 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2778)
03-27 11:45:37.303 22934 22934 E AndroidRuntime:        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
03-27 11:45:37.303 22934 22934 E AndroidRuntime:        at android.app.ActivityThread.-wrap11(Unknown Source:0)
03-27 11:45:37.303 22934 22934 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
03-27 11:45:37.303 22934 22934 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
03-27 11:45:37.303 22934 22934 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:164)
03-27 11:45:37.303 22934 22934 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6494)
03-27 11:45:37.303 22934 22934 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
03-27 11:45:37.303 22934 22934 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
03-27 11:45:37.303 22934 22934 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
03-27 11:45:37.303 22934 22934 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'boolean org.linphone.core.Config.getBool(java.lang.String, java.lang.String, boolean)' on a null object reference
03-27 11:45:37.303 22934 22934 E AndroidRuntime:        at org.linphone.settings.LinphonePreferences.isDarkModeEnabled(LinphonePreferences.java:1411)
03-27 11:45:37.303 22934 22934 E AndroidRuntime:        at org.linphone.utils.ThemableActivity.onCreate(ThemableActivity.java:31)
03-27 11:45:37.303 22934 22934 E AndroidRuntime:        at org.linphone.utils.LinphoneGenericActivity.onCreate(LinphoneGenericActivity.java:31)
03-27 11:45:37.303 22934 22934 E AndroidRuntime:        at org.linphone.LinphoneActivity.onCreate(LinphoneActivity.java:177)
03-27 11:45:37.303 22934 22934 E AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:7009)
03-27 11:45:37.303 22934 22934 E AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:7000)
03-27 11:45:37.303 22934 22934 E AndroidRuntime:        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
03-27 11:45:37.303 22934 22934 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
03-27 11:45:37.303 22934 22934 E AndroidRuntime:        ... 9 more
```

**Comment by Viish** [comment]
This one should be fixed now.
