### ISSUE TITLE
Unable to resume activity {org.linphone.debug/org.linphone.LinphoneActivity}

### ISSUE THREAD

**Issue by brianjmurrell** [BelledonneCommunications/linphone-android#533]
On feature/release-4.1 on a Nexus 5 running LineageOS 15.1:

```
03-28 13:49:47.149 10971 10971 E AndroidRuntime: FATAL EXCEPTION: main
03-28 13:49:47.149 10971 10971 E AndroidRuntime: Process: org.linphone.debug, PID: 10971
03-28 13:49:47.149 10971 10971 E AndroidRuntime: java.lang.RuntimeException: Unable to resume activity {org.linphone.debug/org.linphone.LinphoneActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.preference.Preference.setOnPreferenceChangeListener(android.preference.Preference$OnPreferenceChangeListener)' on a null object reference
03-28 13:49:47.149 10971 10971 E AndroidRuntime:        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3581)
03-28 13:49:47.149 10971 10971 E AndroidRuntime:        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3621)
03-28 13:49:47.149 10971 10971 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1638)
03-28 13:49:47.149 10971 10971 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
03-28 13:49:47.149 10971 10971 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:164)
03-28 13:49:47.149 10971 10971 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6494)
03-28 13:49:47.149 10971 10971 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
03-28 13:49:47.149 10971 10971 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
03-28 13:49:47.149 10971 10971 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
03-28 13:49:47.149 10971 10971 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.preference.Preference.setOnPreferenceChangeListener(android.preference.Preference$OnPreferenceChangeListener)' on a null object reference
03-28 13:49:47.149 10971 10971 E AndroidRuntime:        at org.linphone.settings.SettingsFragment.setTunnelPreferencesListener(SettingsFragment.java:356)
03-28 13:49:47.149 10971 10971 E AndroidRuntime:        at org.linphone.settings.SettingsFragment.setListeners(SettingsFragment.java:232)
03-28 13:49:47.149 10971 10971 E AndroidRuntime:        at org.linphone.settings.SettingsFragment.onStart(SettingsFragment.java:159)
03-28 13:49:47.149 10971 10971 E AndroidRuntime:        at android.app.Fragment.performStart(Fragment.java:2534)
03-28 13:49:47.149 10971 10971 E AndroidRuntime:        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1315)
03-28 13:49:47.149 10971 10971 E AndroidRuntime:        at android.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1557)
03-28 13:49:47.149 10971 10971 E AndroidRuntime:        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1618)
03-28 13:49:47.149 10971 10971 E AndroidRuntime:        at android.app.FragmentManagerImpl.dispatchMoveToState(FragmentManager.java:3027)
03-28 13:49:47.149 10971 10971 E AndroidRuntime:        at android.app.FragmentManagerImpl.dispatchStart(FragmentManager.java:2984)
03-28 13:49:47.149 10971 10971 E AndroidRuntime:        at android.app.FragmentController.dispatchStart(FragmentController.java:189)
03-28 13:49:47.149 10971 10971 E AndroidRuntime:        at android.app.Activity.performStart(Activity.java:7035)
03-28 13:49:47.149 10971 10971 E AndroidRuntime:        at android.app.Activity.performRestart(Activity.java:7104)
03-28 13:49:47.149 10971 10971 E AndroidRuntime:        at android.app.Activity.performResume(Activity.java:7109)
03-28 13:49:47.149 10971 10971 E AndroidRuntime:        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3556)
03-28 13:49:47.149 10971 10971 E AndroidRuntime:        ... 8 more
```

**Comment by Viish** [comment]
Fixed in 4b975a89d42aeeaae49e5ce480d944a300c7f4b1
