### ISSUE TITLE
App crash after change package name 

### ISSUE THREAD

**Issue by anujvats111** [BelledonneCommunications/linphone-android#540]
App get crash after changing package name, It's crashing on lunching time, I have tried all solution and READ.me doc file but each time getting crash. Guys anyone can give any suggestion or solution 
![Uploading logs.PNG…]()

 Process: org.talgotalk, PID: 30688
    java.lang.UnsatisfiedLinkError: No implementation found for boolean org.talgotalk.mediastream.Version.nativeHasNeon() (tried Java_org_talgotalk_mediastream_Version_nativeHasNeon and Java_org_talgotalk_mediastream_Version_nativeHasNeon__)
        at org.talgotalk.mediastream.Version.nativeHasNeon(Native Method)
        at org.talgotalk.mediastream.Version.hasNeon(Version.java:134)
        at org.talgotalk.mediastream.Version.dumpCapabilities(Version.java:161)
        at org.talgotalk.core.FactoryImpl.<clinit>(Factory.java:269)
        at org.talgotalk.core.Factory.instance(Factory.java:37)
        at org.talgotalk.LinphoneService.onCreate(LinphoneService.java:460)
        at android.app.ActivityThread.handleCreateService(ActivityThread.java:3558)
        at android.app.ActivityThread.-wrap4(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1812)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:7000)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)
2019-04-02 11:45:40.072 30618-30618/? A/Adjust: PRODUCTION: Adjust is running in Production mode. Use this setting only for the build that you want to publish. Set the environment to `sandbox` if you want to test your app!
2019-04-02 11:45:40.258 30802-30802/? E/Zygote: isWhitelistProcess - Process is Whitelisted
2019-04-02 11:45:40.374 3488-3488/? E/SignalClusterView: setSlotFocusVisible : subId 2 visible false
2019-04-02 11:45:40.374 3488-3488/? E/SignalClusterView: setSlotFocusVisible : subId 2 visible false
2019-04-02 11:45:40.917 30822-30822/? E/Zygote: isWhitelistProcess - Process is Whitelisted
2019-04-02 11:45:41.167 3005-3086/? E/WindowManager: win=Window{4623b0d u0 Splash Screen org.talgotalk EXITING} destroySurfaces: appStopped=false win.mWindowRemovalAllowed=true win.mRemoveOnExit=true win.mViewVisibility=0, caller=com.android.server.wm.AppWindowToken.destroySurfaces:748 com.android.server.wm.AppWindowToken.destroySurfaces:732 com.android.server.wm.WindowState.onExitAnimationDone:5646 com.android.server.wm.AppWindowAnimator.stepAnimationLocked:517 com.android.server.wm.AppWindowToken.stepAppWindowsAnimation:1745 
2019-04-02 11:45:41.819 3005-4334/? E/KioskModeService: There's no matched data
2019-04-02 11:45:41.856 3005-3024/? E/ViewRootImpl@54643c[talgotalk]: mStopped=false mHasWindowFocus=true mPausedForTransition=false
2019-04-02 11:45:41.860 3005-3024/? E/ViewRootImpl: sendUserActionEvent() returned.
2019-04-02 11:45:42.056 4710-6668/? E/SQLiteLog: (9) statement aborts at 5: [] interrupted

**Comment by Viish** [comment]
You must not change the package name in the code, otherwise yes all JNI calls will be broken.
Check out the feature/release-4.1 branch that has a even simpler way to change package name (see the README).
