### ISSUE TITLE
geeting UnsatisfiedLinkError error while call is runing

### ISSUE THREAD

**Issue by Miteshmakwana73** [BelledonneCommunications/linphone-android#546]
I am getting this error after some time when a call or video call is running.

```
2019-04-03 11:38:55.179 8409-8409/org.linphone E/art: No implementation found for void org.linphone.mediastream.Log.i(java.lang.String) (tried Java_org_linphone_mediastream_Log_i and Java_org_linphone_mediastream_Log_i__Ljava_lang_String_2)
2019-04-03 11:38:55.180 8409-8409/org.linphone D/AndroidRuntime: Shutting down VM
2019-04-03 11:38:55.180 8409-8409/org.linphone E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.linphone, PID: 8409
    java.lang.UnsatisfiedLinkError: No implementation found for void org.linphone.mediastream.Log.i(java.lang.String) (tried Java_org_linphone_mediastream_Log_i and Java_org_linphone_mediastream_Log_i__Ljava_lang_String_2)
        at org.linphone.mediastream.Log.i(Native Method)
        at org.linphone.mediastream.Log.i(Log.java:46)
        at org.linphone.CallOutgoingActivity.checkAndRequestCallPermissions(CallOutgoingActivity.java:284)
        at org.linphone.CallOutgoingActivity.onStart(CallOutgoingActivity.java:186)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1249)
        at android.app.Activity.performStart(Activity.java:6894)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2686)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2784)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1523)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:163)
        at android.app.ActivityThread.main(ActivityThread.java:6238)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)
```
Please help me

**Comment by Viish** [comment]
This means your app has started from an empty context and you didn't load the native libraries (which is automatically done when using any method of the Factory).

**Comment by Miteshmakwana73** [comment]
@Viish what should I do not?

**Comment by Viish** [comment]
Either do not call Log methods before any other Linphone API to ensure libraries will be properly loaded, or do an empty Factory.instance() call.

**Comment by Miteshmakwana73** [comment]
where and how should I call empty Factory.instance()

**Comment by Viish** [comment]
At the begining of each portion of code that could be started off context, like broadcast receivers, and before using the Log class.
Otherwise you can still use the android native logger.
