### ISSUE TITLE
4.1 - crash on settings battery optimisation

### ISSUE THREAD

**Issue by licaon-kter** [BelledonneCommunications/linphone-android#554]
HEAD: 5172bcf5be26e660a393b7ee4b954982b4ed5707
AOSP, Pie

These too were one after another, not sure if related:
```
D AndroidRuntime: Shutting down VM
E AndroidRuntime: FATAL EXCEPTION: main
E AndroidRuntime: Process: org.linphone, PID: 5391
E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Intent.toString()' on a null object reference
E AndroidRuntime:       at android.app.Instrumentation.execStartActivity(Instrumentation.java:1783)
E AndroidRuntime:       at android.app.Activity.startActivityForResult(Activity.java:5276)
E AndroidRuntime:       at android.app.Activity.startActivityFromFragment(Activity.java:5252)
E AndroidRuntime:       at android.app.Activity$HostCallbacks.onStartActivityFromFragment(Activity.java:7942)
E AndroidRuntime:       at android.app.Fragment.startActivity(Fragment.java:1089)
E AndroidRuntime:       at android.app.Fragment.startActivity(Fragment.java:1068)
E AndroidRuntime:       at org.linphone.settings.g$3.a(NetworkSettingsFragment.java:212)
E AndroidRuntime:       at org.linphone.settings.widget.BasicSetting$1.onClick(BasicSetting.java:83)
E AndroidRuntime:       at android.view.View.performClick(View.java:6597)
E AndroidRuntime:       at android.view.View.performClickInternal(View.java:6574)
E AndroidRuntime:       at android.view.View.access$3100(View.java:778)
E AndroidRuntime:       at android.view.View$PerformClick.run(View.java:25889)
E AndroidRuntime:       at android.os.Handler.handleCallback(Handler.java:873)
E AndroidRuntime:       at android.os.Handler.dispatchMessage(Handler.java:99)
E AndroidRuntime:       at android.os.Looper.loop(Looper.java:193)
E AndroidRuntime:       at android.app.ActivityThread.main(ActivityThread.java:6718)
E AndroidRuntime:       at java.lang.reflect.Method.invoke(Native Method)
E AndroidRuntime:       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E AndroidRuntime:       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
D AndroidRuntime: Shutting down VM
E AndroidRuntime: FATAL EXCEPTION: main
E AndroidRuntime: Process: org.linphone, PID: 5464
E AndroidRuntime: java.lang.RuntimeException: Unable to start service org.linphone.LinphoneService@4ce8646 with null: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.content.Intent.getBooleanExtra(java.lang.String, boolean)' on a null object reference
E AndroidRuntime:       at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3724)
E AndroidRuntime:       at android.app.ActivityThread.access$1600(ActivityThread.java:200)
E AndroidRuntime:       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1688)
E AndroidRuntime:       at android.os.Handler.dispatchMessage(Handler.java:106)
E AndroidRuntime:       at android.os.Looper.loop(Looper.java:193)
E AndroidRuntime:       at android.app.ActivityThread.main(ActivityThread.java:6718)
E AndroidRuntime:       at java.lang.reflect.Method.invoke(Native Method)
E AndroidRuntime:       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E AndroidRuntime:       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.content.Intent.getBooleanExtra(java.lang.String, boolean)' on a null object reference
E AndroidRuntime:       at org.linphone.LinphoneService.onStartCommand(LinphoneService.java:243)
E AndroidRuntime:       at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3705)
E AndroidRuntime:       ... 8 more
```

Also, it doesn't matter if battery optimisation is on or off in Android Settings for Linphone

**Comment by Viish** [comment]
Thanks.
Actually the problem was this setting shouldn't be visible if there isn't any power saver app.
Fix is b52bd60ca30dad485e6c6d32dd04611a62f46fe1.
