### ISSUE TITLE
getting RemoteServiceException: Bad notification for startForeground:

### ISSUE THREAD

**Issue by Miteshmakwana73** [BelledonneCommunications/linphone-android#557]
I am getting this error while opening the app in oreo

```
2019-04-09 17:56:57.800 9361-9361/org.linphone E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.linphone, PID: 9361
    android.app.RemoteServiceException: Bad notification for startForeground: java.lang.RuntimeException: invalid channel for service notification: Notification(channel=null pri=-2 contentView=null vibrate=null sound=null defaults=0x0 flags=0x40 color=0x00000000 backgroundColor=0x00000000 category=service vis=SECRET)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1794)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6687)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:810)

```

app is not opening in oreo

**Comment by Miteshmakwana73** [comment]
I am using [this](https://github.com/BelledonneCommunications/linphone) project

**Comment by Miteshmakwana73** [comment]
what should I change in LinphoneService so it runs on oreo

**Comment by Viish** [comment]
Create the notification channel before the foreground service notification.

**Comment by Miteshmakwana73** [comment]
how do I create notification channel

**Comment by Viish** [comment]
Compatibility.createNotificationChannels(mContext);

**Comment by Miteshmakwana73** [comment]
can not resolve `createNotificationChannels(this)`

**Comment by Viish** [comment]
Check out the NotificationsManager manager class in feature/release-4.1 branch.

**Comment by Miteshmakwana73** [comment]
why linphone 4.1 implementing

this  ` androidx.viewpager.widget.ViewPager` insted of `android.support.v4.view.ViewPager`

**Comment by Viish** [comment]
Because we migrated to androix
