### ISSUE TITLE
java.lang.RuntimeException: Unable to start service org.linphone.LinphoneService@8d1ffc9 with null: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.content.Intent.getBooleanExtra(java.lang.String, boolean)' on a null object reference

### ISSUE THREAD

**Issue by brianjmurrell** [BelledonneCommunications/linphone-android#571]
```
04-14 14:51:09.257 27240 27240 E AndroidRuntime: FATAL EXCEPTION: main
04-14 14:51:09.257 27240 27240 E AndroidRuntime: Process: org.linphone.debug, PID: 27240
04-14 14:51:09.257 27240 27240 E AndroidRuntime: java.lang.RuntimeException: Unable to start service org.linphone.LinphoneService@8d1ffc9 with null: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.content.Intent.getBooleanExtra(java.lang.String, boolean)' on a null object reference
04-14 14:51:09.257 27240 27240 E AndroidRuntime:        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4173)
04-14 14:51:09.257 27240 27240 E AndroidRuntime:        at android.app.ActivityThread.-wrap21(Unknown Source:0)
04-14 14:51:09.257 27240 27240 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2119)
04-14 14:51:09.257 27240 27240 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:108)
04-14 14:51:09.257 27240 27240 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:166)
04-14 14:51:09.257 27240 27240 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7523)
04-14 14:51:09.257 27240 27240 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
04-14 14:51:09.257 27240 27240 E AndroidRuntime:        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
04-14 14:51:09.257 27240 27240 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
04-14 14:51:09.257 27240 27240 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.content.Intent.getBooleanExtra(java.lang.String, boolean)' on a null object reference
04-14 14:51:09.257 27240 27240 E AndroidRuntime:        at org.linphone.LinphoneService.onStartCommand(LinphoneService.java:241)
04-14 14:51:09.257 27240 27240 E AndroidRuntime:        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4145)
04-14 14:51:09.257 27240 27240 E AndroidRuntime:        ... 8 more
```

**Comment by Viish** [comment]
Thanks.
Fixed in 335c677c7f3f31e92e89340ec2eb29d75da7ba8c
