### ISSUE TITLE
Sip Registration On My Server (Vos3000) failed

### ISSUE THREAD

**Issue by WilfriedTIANI** [BelledonneCommunications/linphone-android#599]
Morning all, 

I tried to build and install Linphone-Android with AndroidStudio after installing on my smartphone, i tried to connect Linphone to my SipServer with registration account. But not registring on server 

I shared procedure and Variable value here.

**_ProxyConfig return null_**

Please Can you help me ? 

![ConfigurationSip](https://user-images.githubusercontent.com/29524107/56899229-d8fcfb80-6a8a-11e9-8beb-97a306300f58.JPEG)
![JavaSip](https://user-images.githubusercontent.com/29524107/56899230-d8fcfb80-6a8a-11e9-9719-2350bbd59683.png)
![ChoixSip](https://user-images.githubusercontent.com/29524107/56899231-d8fcfb80-6a8a-11e9-93f1-69e18d8c483f.JPEG)

**Comment by elagrari** [comment]
salut 
j'ai un problème au Temp d'enregistrement 
le résultat :
 -pas de message d erreur
-comme un blocage : rien d exécution  
-sa veur dir j ai une template de linphone pas de fonctionnement 
si vous avez des solution repond moi et merci beaucoup ^^

**Comment by Viish** [comment]
Wilfried it means you haven't correctly filled the fields.

Elagari désolé si vous n'êtes pas développeur je ne peux pas vous aider

**Comment by WilfriedTIANI** [comment]
Bonjour en laissez moi faire un nouveau test et vous l'envoyer.
Je vais prendre les logs aussi

Le mar. 30 avr. 2019 à 07:22, Sylvain Berfini <notifications@github.com> a
écrit :

**Comment by WilfriedTIANI** [comment]
Bonsoir , j'ai fait un test et voici la vidéo du résultat

https://youtu.be/A4_J8OzFSdw

PS : Rien ne se passe

Le mer. 1 mai 2019 à 15:27, Wilfried Tiani <wilfriedtiani@gmail.com> a
écrit :

**Comment by WilfriedTIANI** [comment]
Et lorsque j'essaye de créer un compte LinPhone , 

Voici le crash que j'ai 




java.lang.RuntimeException: Unable to start activity ComponentInfo{org.linphone.debug/org.linphone.assistant.MenuAssistantActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.String org.linphone.core.Config.getString(java.lang.String, java.lang.String, java.lang.String)' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2814)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892)
	at android.app.ActivityThread.-wrap11(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1613)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:176)
	at android.app.ActivityThread.main(ActivityThread.java:6635)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)
Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.String org.linphone.core.Config.getString(java.lang.String, java.lang.String, java.lang.String)' on a null object reference
	at org.linphone.settings.LinphonePreferences.getXmlrpcUrl(LinphonePreferences.java:864)
	at org.linphone.assistant.AssistantActivity.onCreate(AssistantActivity.java:57)
	at org.linphone.assistant.MenuAssistantActivity.onCreate(MenuAssistantActivity.java:37)
	at android.app.Activity.performCreate(Activity.java:7084)
	at android.app.Activity.performCreate(Activity.java:7075)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1215)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2767)
	... 9 more

**Comment by WilfriedTIANI** [comment]
A defaut  svp quelle version telecharger pour avoir la meme version de softphone que celle qui est  sur le playStore

**Comment by WilfriedTIANI** [comment]
It's ok i take the actuall PlayStore Version and working fine 

I will try to upgrade commit/commit and check difference

**Comment by WilfriedTIANI** [comment]
Morning @Viish  
Je sais que le problème est déjà ferme(C'est moi qui ai ferme) mais je voulais juste faire un partage sur ce que j'ai eu comme retour en testant toutes les versions publiée.
 En fait je le problème d'authentification se pose lors du passage de la version 
**aa608f2e726f8bbdb0e98d8ea297891237bfa99e** du    24-04-2019 a  08h38  a la version
**5197d5b926aecb9e23424f3c5771da3f94859428** du    24-04-2019 a 10h18  

J'ai remarque après ce changement l'application ne se connecte plus au serveur.

Pour tester j'utilise un téléphone avec les caractéristiques suivantes :
Fabriquant : Xiaomi
Model : Remi Note 5 
Version Android : 8.1.0 -> OPM1.171019.011
Version MIUI : MIUI Global 10.2.1 Stable -> 10.2.2.0(OEIMIXM)
Nom Model : MEE7S

**Comment by Viish** [comment]
@WilfriedTIANI You shouldn't be on commit 5197d5b, it is the first commit on a feature development branch and indeed contains many issues. You should stay on master or release/4.1 until this branch is finished and merged.
