### ISSUE TITLE
4.1 crash on pop-up touch

### ISSUE THREAD

**Issue by licaon-kter** [BelledonneCommunications/linphone-android#651]
AOSP 9 or Sony 6.0.1, F-Droid

Steps:
* make a video call
* press home
* see pop-up video
* touch it (expecting to go back, move it or maybe offer an option to resize, etc)

Result:
```
05-22 15:16:25.226 16408 16408 D AndroidRuntime: Shutting down VM
05-22 15:16:25.228 16408 16408 E AndroidRuntime: FATAL EXCEPTION: main
05-22 15:16:25.228 16408 16408 E AndroidRuntime: Process: org.linphone, PID: 16408
05-22 15:16:25.228 16408 16408 E AndroidRuntime: android.util.AndroidRuntimeException: Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?
05-22 15:16:25.228 16408 16408 E AndroidRuntime: 	at android.app.ContextImpl.startActivity(ContextImpl.java:912)
05-22 15:16:25.228 16408 16408 E AndroidRuntime: 	at android.app.ContextImpl.startActivity(ContextImpl.java:888)
05-22 15:16:25.228 16408 16408 E AndroidRuntime: 	at android.content.ContextWrapper.startActivity(ContextWrapper.java:379)
05-22 15:16:25.228 16408 16408 E AndroidRuntime: 	at org.linphone.views.j$1.onClick(LinphoneTextureViewOverlay.java:112)
05-22 15:16:25.228 16408 16408 E AndroidRuntime: 	at android.view.View.performClick(View.java:6617)
05-22 15:16:25.228 16408 16408 E AndroidRuntime: 	at android.view.View.performClickInternal(View.java:6594)
05-22 15:16:25.228 16408 16408 E AndroidRuntime: 	at android.view.View.access$3100(View.java:778)
05-22 15:16:25.228 16408 16408 E AndroidRuntime: 	at android.view.View$PerformClick.run(View.java:25906)
05-22 15:16:25.228 16408 16408 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:873)
05-22 15:16:25.228 16408 16408 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
05-22 15:16:25.228 16408 16408 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:193)
05-22 15:16:25.228 16408 16408 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6723)
05-22 15:16:25.228 16408 16408 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-22 15:16:25.228 16408 16408 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:495)
05-22 15:16:25.228 16408 16408 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by Viish** [comment]
Thanks !
Fixed in 20b84e55f17edb67d0e8f4cb09f9b4812bc5e1b5
