### ISSUE TITLE
Remote provisioning file crashes Linphone on Android

### ISSUE THREAD

**Issue by cimm** [BelledonneCommunications/linphone-android#703]
I have the following (redacted) remote provisioning XML file which gets loaded when Linphone boots and asks the user to log in to their SIP account. Scanning a QR code to setup a SIP phone is an awesome experience BTW, but that's not why I opened this issue. Loading the config below works fine on iOS but crashes Linphone on Android.

When you press the "Connect" button on Android Linphone crashes. Restarting Linphone brings you back to the login screen (fields are empty again) and when you try to connect it crashes again.

```xml
<config xmlns="http://www.linphone.org/xsds/lpconfig.xsd"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.linphone.org/xsds/lpconfig.xsd lpconfig.xsd">

  <section name="sip">
    <entry name="register_only_when_network_is_up" overwrite="true">1</entry>
  </section>

  <section name="app">
    <entry name="push_notification" overwrite="true">1</entry>
    <entry name="auto_start" overwrite="true">1</entry>
    <entry name="background_mode" overwrite="true">1</entry>
    <entry name="show_login_view" overwrite="true">1</entry>
  </section>

  <section name="proxy_default_values">
    <entry name="reg_proxy" overwrite="true">sip:xxx.sip.us1.twilio.com;transport=tls</entry>
    <entry name="reg_route" overwrite="true">sip:xxx.sip.us1.twilio.com;transport=tls</entry>
    <entry name="reg_identity" overwrite="true">sip:?@xxx.sip.us1.twilio.com</entry>
    <entry name="reg_expires" overwrite="true">3600</entry>
    <entry name="reg_sendregister" overwrite="true">1</entry>
    <entry name="publish" overwrite="true">0</entry>
    <entry name="push_notification_allowed" overwrite="true">1</entry>
  </section>

  <section name="misc">
    <entry name="transient_provisioning">1</entry>
  </section>
</config>
```

Using version 4.1.1 from F-Droid.

Any ideas?

**Comment by Viish** [comment]
Hi,

Can you catch the stacktrace of the crash through adb ?

**Comment by Viish** [comment]
Try to edit your rc with the following changes:
```
<entry name="reg_proxy" overwrite="true">&lt;sip:xxx.sip.us1.twilio.com;transport=tls&gt;</entry>
<entry name="reg_route" overwrite="true">&lt;sip:xxx.sip.us1.twilio.com;transport=tls&gt;</entry>
```

**Comment by cimm** [comment]
Thanks, the `&lt;` trick didn't work. Any pointers on how to catch the stracktrace through `adb`? I know how to connect a device via `adb` byt how do I "catch a stracktrace"?

**Comment by cimm** [comment]
```
07-05 10:21:06.378   664  2776 D ConnectivityService: releasing NetworkRequest [ TRACK_DEFAULT id=14, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Unwanted:  Uid: 10073] ] (release request)
07-05 10:21:06.685  8571  8903 I OMXClient: IOmx service obtained
07-05 10:21:06.685   384   442 I OMXMaster: makeComponentInstance(OMX.qcom.video.encoder.avc) in <unknown> process
07-05 10:21:06.831  8571  8917 I OMXClient: IOmx service obtained
07-05 10:21:06.832   384   442 I OMXMaster: makeComponentInstance(OMX.qcom.video.decoder.avc) in <unknown> process
07-05 10:21:06.880  8571  8571 W MediaCodec-JNI: try to release MediaCodec from JMediaCodec::~JMediaCodec()...
07-05 10:21:06.881  8571  8571 W MediaCodec-JNI: done releasing MediaCodec from JMediaCodec::~JMediaCodec().
07-05 10:21:06.881  8571  8571 W System.err: java.lang.IllegalArgumentException: Failed to initialize video/hevc, error 0xfffffffe
07-05 10:21:06.881  8571  8571 W System.err: 	at android.media.MediaCodec.native_setup(Native Method)
07-05 10:21:06.881  8571  8571 W System.err: 	at android.media.MediaCodec.<init>(MediaCodec.java:1811)
07-05 10:21:06.882  8571  8571 W System.err: 	at android.media.MediaCodec.createEncoderByType(MediaCodec.java:1777)
07-05 10:21:06.882  8571  8571 W System.err: 	at org.linphone.core.CoreImpl.start(Native Method)
07-05 10:21:06.882  8571  8571 W System.err: 	at org.linphone.core.CoreImpl.start(Core.java:5319)
07-05 10:21:06.882  8571  8571 W System.err: 	at org.linphone.a.m(LinphoneManager.java:686)
07-05 10:21:06.882  8571  8571 W System.err: 	at org.linphone.assistant.j.onClick(RemoteProvisioningFragment.java:68)
07-05 10:21:06.882  8571  8571 W System.err: 	at android.view.View.performClick(View.java:6597)
07-05 10:21:06.882  8571  8571 W System.err: 	at android.view.View.performClickInternal(View.java:6574)
07-05 10:21:06.882  8571  8571 W System.err: 	at android.view.View.access$3100(View.java:778)
07-05 10:21:06.882  8571  8571 W System.err: 	at android.view.View$PerformClick.run(View.java:25885)
07-05 10:21:06.882  8571  8571 W System.err: 	at android.os.Handler.handleCallback(Handler.java:873)
07-05 10:21:06.882  8571  8571 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:99)
07-05 10:21:06.882  8571  8571 W System.err: 	at android.os.Looper.loop(Looper.java:193)
07-05 10:21:06.882  8571  8571 W System.err: 	at android.app.ActivityThread.main(ActivityThread.java:6718)
07-05 10:21:06.882  8571  8571 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
07-05 10:21:06.882  8571  8571 W System.err: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
07-05 10:21:06.882  8571  8571 W System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
07-05 10:21:06.890  8571  8923 I OMXClient: IOmx service obtained
07-05 10:21:06.891   384   442 I OMXMaster: makeComponentInstance(OMX.google.hevc.decoder) in <unknown> process
07-05 10:21:06.943   664  2978 D ConnectivityService: requestNetwork for uid/pid:10073/8571 NetworkRequest [ TRACK_DEFAULT id=15, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Unwanted:  Uid: 10073] ]
07-05 10:21:06.944   664  2803 D Ethernet: got request NetworkRequest [ TRACK_DEFAULT id=15, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Unwanted:  Uid: 10073] ] with score 60
07-05 10:21:06.945   664  2773 D WIFI    : got request NetworkRequest [ TRACK_DEFAULT id=15, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Unwanted:  Uid: 10073] ] with score 60
07-05 10:21:06.945   664  2773 D WIFI_UT : got request NetworkRequest [ TRACK_DEFAULT id=15, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Unwanted:  Uid: 10073] ] with score 60
07-05 10:21:06.945  2915  2915 D PhoneSwitcherNetworkRequstListener: got request NetworkRequest [ TRACK_DEFAULT id=15, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Unwanted:  Uid: 10073] ] with score 60
07-05 10:21:06.962  8571  8571 I Choreographer: Skipped 39 frames!  The application may be doing too much work on its main thread.
07-05 10:21:06.975   305  3038 D SurfaceFlinger: duplicate layer name: changing org.linphone/org.linphone.assistant.AssistantActivity to org.linphone/org.linphone.assistant.AssistantActivity#1
07-05 10:21:06.980  8571  8592 W Adreno-EGL: <qeglDrvAPI_eglGetConfigAttrib:607>: EGL_BAD_ATTRIBUTE
07-05 10:21:06.981  8571  8592 D vndksupport: Loading /vendor/lib/hw/gralloc.msm8974.so from current namespace instead of sphal namespace.
07-05 10:21:07.171   305  2808 D SurfaceFlinger: duplicate layer name: changing Surface(name=5320f81 org.linphone/org.linphone.assistant.AssistantActivity)/@0x4c805fe - animation-leash to Surface(name=5320f81 org.linphone/org.linphone.assistant.AssistantActivity)/@0x4c805fe - animation-leash#1
07-05 10:21:07.175   305   439 D SurfaceFlinger: duplicate layer name: changing Surface(name=Dim Layer for - Task=94)/@0x43d57ac - animation-leash to Surface(name=Dim Layer for - Task=94)/@0x43d57ac - animation-leash#1
07-05 10:21:07.181   664  3437 I ActivityManager: START u0 {cmp=org.linphone/.LinphoneActivity (has extras)} from uid 10073
07-05 10:21:07.192   664  6035 I ActivityManager: START u0 {cmp=org.linphone/.LinphoneActivity (has extras)} from uid 10073
07-05 10:21:07.198   664  7441 W ActivityManager: Duplicate finish request for ActivityRecord{aaabe87 u0 org.linphone/.assistant.AssistantActivity t94 f}
07-05 10:21:07.225  8571  8571 W ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@5e36f55
07-05 10:21:07.234   664  2978 I ActivityManager: START u0 {cmp=org.linphone/.assistant.RemoteProvisioningLoginActivity (has extras)} from uid 10073
07-05 10:21:07.258  8571  8571 W ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@5040409
07-05 10:21:07.312  8571  8592 W Adreno-EGL: <qeglDrvAPI_eglGetConfigAttrib:607>: EGL_BAD_ATTRIBUTE
07-05 10:21:07.312  8571  8592 D vndksupport: Loading /vendor/lib/hw/gralloc.msm8974.so from current namespace instead of sphal namespace.
07-05 10:21:07.341   305  2808 W SurfaceFlinger: Attempting to set client state on removed layer: org.linphone/org.linphone.assistant.AssistantActivity#1
07-05 10:21:07.341   305  2808 W SurfaceFlinger: Attempting to set client state on removed layer: Dim Layer for - Task=94#0
07-05 10:21:07.341   305  2808 W SurfaceFlinger: Attempting to destroy on removed layer: org.linphone/org.linphone.assistant.AssistantActivity#1
07-05 10:21:07.341   305  2808 W SurfaceFlinger: Attempting to destroy on removed layer: Dim Layer for - Task=94#0
07-05 10:21:26.645   383   383 W wificond: Copy constructor is only used for unit tests
07-05 10:21:26.646   383   383 W wificond: Failed to get NL80211_ATTR_EXT_FEATURES
07-05 10:21:26.649   383   383 W wificond: Copy constructor is only used for unit tests
07-05 10:21:26.650   383   383 W wificond: Failed to get NL80211_ATTR_EXT_FEATURES
07-05 10:21:26.652   383   383 W wificond: Copy constructor is only used for unit tests
07-05 10:21:26.653   383   383 W wificond: Failed to get NL80211_ATTR_EXT_FEATURES
07-05 10:21:28.077  2812  2812 I LatinIME: Starting input. Cursor position = 0,0
07-05 10:21:28.148  2812  5145 W Adreno-EGL: <qeglDrvAPI_eglGetConfigAttrib:607>: EGL_BAD_ATTRIBUTE
07-05 10:21:28.149  2812  5145 D vndksupport: Loading /vendor/lib/hw/gralloc.msm8974.so from current namespace instead of sphal namespace.
07-05 10:21:30.515   664  2892 D WificondControl: Scan result ready event
07-05 10:21:30.520   664  1366 I EthernetTracker: interfaceLinkStateChanged, iface: wlan0, up: true
07-05 10:21:33.745  2812  2812 I LatinIME: Starting input. Cursor position = 0,0
07-05 10:22:00.517   664   675 I system_server: Background concurrent copying GC freed 149763(5MB) AllocSpace objects, 29(1252KB) LOS objects, 42% free, 8MB/14MB, paused 337us total 173.136ms
07-05 10:22:24.354   664  6035 W ActivityManager: Unable to start service Intent { act=com.android.launcher3.WINDOW_OVERLAY dat=app://com.android.launcher3:10089?v=7&cv=9 pkg=com.google.android.googlequicksearchbox } U=0: not found
07-05 10:22:24.368  3499  3578 W Adreno-EGL: <qeglDrvAPI_eglGetConfigAttrib:607>: EGL_BAD_ATTRIBUTE
07-05 10:22:24.369  3499  3578 D vndksupport: Loading /vendor/lib/hw/gralloc.msm8974.so from current namespace instead of sphal namespace.
07-05 10:22:24.899   664  4086 I OpenGLRenderer: Initialized EGL, version 1.4
07-05 10:22:24.899   664  4086 D OpenGLRenderer: Swap behavior 1
07-05 10:22:24.902   664  4086 W Adreno-EGL: <qeglDrvAPI_eglGetConfigAttrib:607>: EGL_BAD_ATTRIBUTE
07-05 10:22:24.916   305  3339 W SurfaceFlinger: Attempting to destroy on removed layer: AppWindowToken{e02f274 token=Token{605ca47 ActivityRecord{cbea186 u0 org.linphone/.assistant.RemoteProvisioningLoginActivity t94}}}#0
```

**Comment by Viish** [comment]
Actually this doesn't help.
Have you enabled debug logs in the advanced settings ?
I'll need the full logs please.

**Comment by Viish** [comment]
I don't know what this get_remote_provisioning_filename method is.
For sure it's not implemented on our subscribe.linphone.org service.
I guess you have made some changes either to our lib or our app ?

**Comment by cimm** [comment]
No, I just downloaded Linphone via the F-Droid app.

**Comment by Viish** [comment]
Ok that's why it crashes on Android and not iOS.
On iOS my guess is we don't try to call that method (because it doesn't exists) and on Android for some reason we try to.
I re-wrote the whole assistant on master branch after 4.1 release, so this won't happen anymore.
Next version (4.2) is planned for August. In the meantime you can use the master branch nightly snapshots at https://linphone.org/snapshots/android/

**Comment by cimm** [comment]
Great news! I'll try out the 4.2 release when it's available. Thank you!
