### ISSUE TITLE
Unable to instantiate service org.packagename.firebase.FirebaseMessaging with FCM

### ISSUE THREAD

**Issue by farhat97** [BelledonneCommunications/linphone-android#729]
Hello,

I keep having this problem when trying to integrate my own Firebase project with Linphone. I already successfully changed the google-services.json file and the app will run just fine. However, whenever I send a test notification form the Firebase console, I get the following error: 

java.lang.RuntimeException: Unable to instantiate service org.vpbxcommunicator.firebase.FirebaseMessaging: java.lang.ClassNotFoundException: Didn't find class "org.vpbxcommunicator.firebase.FirebaseMessaging" on path: DexPathList[[zip file "/data/app/org.vpbxCommunicator.debug-UVlPBKlrrM4goWsx3K6E1A==/base.apk"],nativeLibraryDirectories=[/data/app/org.vpbxCommunicator.debug-UVlPBKlrrM4goWsx3K6E1A==/lib/arm, /data/app/org.vpbxCommunicator.debug-UVlPBKlrrM4goWsx3K6E1A==/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
at android.app.ActivityThread.handleCreateService(ActivityThread.java:3744)
        at android.app.ActivityThread.access$1400(ActivityThread.java:237)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7073)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
Caused by: java.lang.ClassNotFoundException: Didn't find class "org.vpbxcommunicator.firebase.FirebaseMessaging" on path: DexPathList[[zip file "/data/app/org.vpbxCommunicator.debug-nfAjjMPyhP-q6oOvo2E4GQ==/base.apk"],nativeLibraryDirectories=[/data/app/org.vpbxCommunicator.debug-nfAjjMPyhP-q6oOvo2E4GQ==/lib/arm, /data/app/org.vpbxCommunicator.debug-nfAjjMPyhP-q6oOvo2E4GQ==/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.app.AppComponentFactory.instantiateService(AppComponentFactory.java:103)
        at androidx.core.app.CoreComponentFactory.instantiateService(CoreComponentFactory.java:66)
        at android.app.ActivityThread.handleCreateService(ActivityThread.java:3739)
        at android.app.ActivityThread.access$1400(ActivityThread.java:237) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7073) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965) 

I also noticed that FirebasePushHelper is not being found when called in PushNotificationUtils.java. In the meantime, I changed the instantiation to the one changed in this commit: https://gitlab.linphone.org/BC/public/linphone-android/commit/feb6312c93769fcf55938e711dc47da4e0753f75

Do you have any ideas on how to solve this problem?

**Comment by Viish** [comment]
Hi,
I guess you changed the value at this line:
https://gitlab.linphone.org/BC/public/linphone-android/commit/feb6312c93769fcf55938e711dc47da4e0753f75#86a547d8f76b198cbe03637f77fbc0c5b0a04321_0_31
?

**Comment by farhat97** [comment]
Yes, I did
And I think I fixed this error by commenting out any part that involved checking for `firebaseEnabled()`; essentially, always instantiating Firebase dependencies

Now I can get push notifications for text messages. Not sure how to approach calls.
