### ISSUE TITLE
revoked permission android.permission.CALL_PHONE

### ISSUE THREAD

**Issue by brianjmurrell** [BelledonneCommunications/linphone-android#747]
A crash I just happened to notice while perusing `adb logcat`:

```
08-05 10:17:47.383 14469 14469 E AndroidRuntime: FATAL EXCEPTION: main
08-05 10:17:47.383 14469 14469 E AndroidRuntime: Process: org.linphone, PID: 14469
08-05 10:17:47.383 14469 14469 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{org.linphone/org.linphone.LinphoneActivity}: java.lang.SecurityException: Permission Denial: starting Intent { act=android.intent.action.CALL dat=tel:xxxxxxxxxxxx flg=0x13000000 cmp=org.linphone/.LinphoneLauncherActivity } from ProcessRecord{b9f3029 14469:org.linphone/u0a103} (pid=14469, uid=10103) with revoked permission android.permission.CALL_PHONE
08-05 10:17:47.383 14469 14469 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3297)
08-05 10:17:47.383 14469 14469 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3405)
08-05 10:17:47.383 14469 14469 E AndroidRuntime: 	at android.app.ActivityThread.-wrap12(Unknown Source:0)
08-05 10:17:47.383 14469 14469 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1994)
08-05 10:17:47.383 14469 14469 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:108)
08-05 10:17:47.383 14469 14469 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:166)
08-05 10:17:47.383 14469 14469 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7523)
08-05 10:17:47.383 14469 14469 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
08-05 10:17:47.383 14469 14469 E AndroidRuntime: 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
08-05 10:17:47.383 14469 14469 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
08-05 10:17:47.383 14469 14469 E AndroidRuntime: Caused by: java.lang.SecurityException: Permission Denial: starting Intent { act=android.intent.action.CALL dat=tel:xxxxxxxxxxxx flg=0x13000000 cmp=org.linphone/.LinphoneLauncherActivity } from ProcessRecord{b9f3029 14469:org.linphone/u0a103} (pid=14469, uid=10103) with revoked permission android.permission.CALL_PHONE
08-05 10:17:47.383 14469 14469 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:1946)
08-05 10:17:47.383 14469 14469 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:1892)
08-05 10:17:47.383 14469 14469 E AndroidRuntime: 	at android.app.IActivityManager$Stub$Proxy.startActivity(IActivityManager.java:4394)
08-05 10:17:47.383 14469 14469 E AndroidRuntime: 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1631)
08-05 10:17:47.383 14469 14469 E AndroidRuntime: 	at android.app.Activity.startActivityForResult(Activity.java:4762)
08-05 10:17:47.383 14469 14469 E AndroidRuntime: 	at androidx.fragment.app.e.startActivityForResult(FragmentActivity.java:657)
08-05 10:17:47.383 14469 14469 E AndroidRuntime: 	at android.app.Activity.startActivityForResult(Activity.java:4702)
08-05 10:17:47.383 14469 14469 E AndroidRuntime: 	at androidx.fragment.app.e.startActivityForResult(FragmentActivity.java:644)
08-05 10:17:47.383 14469 14469 E AndroidRuntime: 	at android.app.Activity.startActivity(Activity.java:5123)
08-05 10:17:47.383 14469 14469 E AndroidRuntime: 	at android.app.Activity.startActivity(Activity.java:5091)
08-05 10:17:47.383 14469 14469 E AndroidRuntime: 	at org.linphone.utils.LinphoneGenericActivity.onCreate(LinphoneGenericActivity.java:41)
08-05 10:17:47.383 14469 14469 E AndroidRuntime: 	at org.linphone.LinphoneActivity.onCreate(LinphoneActivity.java:179)
08-05 10:17:47.383 14469 14469 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:7383)
08-05 10:17:47.383 14469 14469 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1218)
08-05 10:17:47.383 14469 14469 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3250)
08-05 10:17:47.383 14469 14469 E AndroidRuntime: 	... 9 more
```

**Comment by driesken** [comment]
Are you sure that you have granted al permissions to Linphone?

**Comment by Viish** [comment]
@brianjmurrell I see you are not up-to-date, please update and tell me if the issue is still here.

**Comment by brianjmurrell** [comment]
> Are you sure that you have granted al permissions to Linphone?

https://photos.app.goo.gl/MzocF4qShY5Yv9aw9

> I see you are not up-to-date, please update and tell me if the issue is still here.

Where/how do you see that?  AFAIK, I am up to date:

```
~/linphone-android$ git fetch --all
Fetching origin
Fetching gmobile-android
```

**Comment by Viish** [comment]
git fetch only search for new commits but that's all.
Use git pull to get them.
You can use git-describe to see where you're at (latest one is 4.1-97-g89941db5).

**Comment by Viish** [comment]
> That seems to be master. I am on release/4.1. Is that not really where the current stable release should be considered from? Should daily-driver builds really be done from master and not a release/ branch?

Indeed the release/4.1 is the latest release, but between releases it's the master branch that is up-to-date. And it is almost as much stable as the release thanks to our CI methods.

**Comment by brianjmurrell** [comment]
> And it is almost as much stable

**Almost** as much stable is not good enough to give to users.  They're number one requirement is stability.

**Comment by Viish** [comment]
Sure, but as I told you I can't maintain the release/4.1 branch, so master might be even more stable.
