### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke interface method 'boolean org.linphone.core.ChatRoom.hasCapability(int)' on a null object reference

### ISSUE THREAD

**Issue by brianjmurrell** [BelledonneCommunications/linphone-android#762]
I have an SMS chat that shows a new message in it in the messages summary, and when I open the chat this is all that I see:
![empty chat window](http://brian.interlinx.bc.ca/Screenshot_20190906-085427.jpg)

The message I see in the message list window (obviously) just doesn't show up there.  The above window thinks the sender is still sending.  It is not.  It was a SIP MESSAGE.

And then there is the scary looking red shield with the exclamation in it.  What is that?  When I press it, Linphone crashes with:

```
09-06 08:54:32.329 21110 21110 E AndroidRuntime: Process: org.linphone.debug, PID: 21110
09-06 08:54:32.329 21110 21110 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke interface method 'boolean org.linphone.core.ChatRoom.hasCapability(int)' on a null object reference
09-06 08:54:32.329 21110 21110 E AndroidRuntime:        at org.linphone.chat.ChatMessagesFragment$1.onClick(ChatMessagesFragment.java:162)
09-06 08:54:32.329 21110 21110 E AndroidRuntime:        at android.view.View.performClick(View.java:6291)
09-06 08:54:32.329 21110 21110 E AndroidRuntime:        at android.view.View$PerformClick.run(View.java:24931)
09-06 08:54:32.329 21110 21110 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:808)
09-06 08:54:32.329 21110 21110 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:101)
09-06 08:54:32.329 21110 21110 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:166)
09-06 08:54:32.329 21110 21110 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7523)
09-06 08:54:32.329 21110 21110 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
09-06 08:54:32.329 21110 21110 E AndroidRuntime:        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
09-06 08:54:32.329 21110 21110 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
09-06 08:54:32.332  1104  1272 D WifiConfigStore: Writing to stores completed in 12 ms.
09-06 08:54:32.334  1104  6363 W ActivityManager:   Force finishing activity org.linphone.debug/org.linphone.LinphoneActivity
09-06 08:54:32.345  1104  3839 E ReportTools: This is not beta user build
09-06 08:54:32.346 21110 21110 I Process : Sending signal. PID: 21110 SIG: 9
09-06 08:54:32.347  1712  2183 I AppManager: removeProcessDependency pid:21110

```

**Comment by Viish** [comment]
For some reason the app has displayed you a chatroom that doesn't exists, so yes the display doesn't match.
The scary red icon is supposed to mean (when the chatroom pointer is correct) that the chatroom is encrypted but a man in the middle has been detected.

**Comment by brianjmurrell** [comment]
This is the `SIP MESSAGE` that causes this issue:

```
MESSAGE sip:brian_h8@10.75.22.32:33848;transport=tcp;app-id=[redacted];pn-type=firebase;pn-timeout=0;pn-tok=[redacted];pn-silent=1 SIP/2.0
Via: SIP/2.0/TCP 10.75.22.8:5060;rport;branch=z9hG4bKPj1b327cdd-cec3-4173-a4fe-48a7e8dc5651;alias
From: <sip:pbx>;tag=f6045c0a-0fce-48b4-a650-d4c3cba55189
To: <sip:brian_h8@10.75.22.32;app-id=[redacted];pn-type=firebase;pn-timeout=0;pn-tok=[redacted];pn-silent=1>
Contact: <sip:brian_h8@10.75.22.8:5060;transport=TCP>
Call-ID: 45c3948f-eea7-4dae-ab7c-f4e4d5622740
CSeq: 26649 MESSAGE
Max-Forwards: 70
User-Agent: Asterisk PBX 13.28.0
Content-Type: text/plain
Content-Length:    60
```

The `From:` address is badly formed, indeed.  But the app shouldn't crash in that case.  Nor should it have that scary icon, nor should it fail to show the message in the chat, etc.

**Comment by Viish** [comment]
Indeed, I'll fix it.
