### ISSUE TITLE
when answer the call

### ISSUE THREAD

**Issue by wirelessmundi** [BelledonneCommunications/linphone-android#775]
on outgoing call when the other end answer the call: 

--------- beginning of crash
2019-09-16 12:16:22.613 12992-12992/org.linphone.debug E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.linphone.debug, PID: 12992
    java.lang.RuntimeException: Unable to start activity ComponentInfo{org.linphone.debug/org.linphone.call.CallActivity}: android.view.InflateException: Binary XML file line #23: Binary XML file line #23: Error inflating class org.linphone.mediastream.video.capture.CaptureTextureView
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2824)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2899)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1600)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6610)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
     Caused by: android.view.InflateException: Binary XML file line #23: Binary XML file line #23: Error inflating class org.linphone.mediastream.video.capture.CaptureTextureView
     Caused by: android.view.InflateException: Binary XML file line #23: Error inflating class org.linphone.mediastream.video.capture.CaptureTextureView
     Caused by: java.lang.ClassNotFoundException: Didn't find class "org.linphone.mediastream.video.capture.CaptureTextureView" on path: DexPathList[[zip file "/data/app/org.linphone.debug-CVQDk_vyR43pPaiIVZo3aw==/base.apk", zip file "/data/app/org.linphone.debug-CVQDk_vyR43pPaiIVZo3aw==/split_lib_dependencies_apk.apk", zip file "/data/app/org.linphone.debug-CVQDk_vyR43pPaiIVZo3aw==/split_lib_resources_apk.apk", zip file "/data/app/org.linphone.debug-CVQDk_vyR43pPaiIVZo3aw==/split_lib_slice_0_apk.apk", zip file "/data/app/org.linphone.debug-CVQDk_vyR43pPaiIVZo3aw==/split_lib_slice_1_apk.apk", zip file "/data/app/org.linphone.debug-CVQDk_vyR43pPaiIVZo3aw==/split_lib_slice_2_apk.apk", zip file "/data/app/org.linphone.debug-CVQDk_vyR43pPaiIVZo3aw==/split_lib_slice_3_apk.apk", zip file "/data/app/org.linphone.debug-CVQDk_vyR43pPaiIVZo3aw==/split_lib_slice_4_apk.apk", zip file "/data/app/org.linphone.debug-CVQDk_vyR43pPaiIVZo3aw==/split_lib_slice_5_apk.apk", zip file "/data/app/org.linphone.debug-CVQDk_vyR43pPaiIVZo3aw==/split_lib_slice_6_apk.apk", zip file "/data/app/org.linphone.debug-CVQDk_vyR43pPaiIVZo3aw==/split_lib_slice_7_apk.apk", zip file "/data/app/org.linphone.debug-CVQDk_vyR43pPaiIVZo3aw==/split_lib_slice_8_apk.apk", zip file "/data/app/org.linphone.debug-CVQDk_vyR43pPaiIVZo3aw==/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/org.linphone.debug-CVQDk_vyR43pPaiIVZo3aw==/lib/arm64, /data/app/org.linphone.debug-CVQDk_vyR43pPaiIVZo3aw==/base.apk!/lib/arm64-v8a, /data/app/org.linphone.debug-CVQDk_vyR43pPaiIVZo3aw==/split_lib_dependencies_apk.apk!/lib/arm64-v8a, /data/app/org.linphone.debug-CVQDk_vyR43pPaiIVZo3aw==/split_lib_resources_apk.apk!/lib/arm64-v8a, /data/app/org.linphone.debug-CVQDk_vyR43pPaiIVZo3aw==/split_lib_slice_0_apk.apk!/lib/arm64-v8a, /data/app/org.linphone.debug-CVQDk_vyR43pPaiIVZo3aw==/split_lib_slice_1_apk.apk!/lib/arm64-v8a, /data/app/org.linphone.debug-CVQDk_vyR43pPaiIVZo3aw==/split_lib_slice_2_apk.apk!/lib/arm64-v8a, /data/app/org.linphone.debug-CVQDk_vyR43pPaiIVZo3aw==/split_lib_slice_3_apk.apk!/lib/arm64-v8a, /data/app/org.linphone.debug-CVQDk_vyR43pPaiIVZo3aw==/split_lib_slice_4_apk.apk!/lib/arm64-v8a, /data/app/org.linphone.debug-CVQDk_vyR43pPaiIVZo3aw==/split_lib_slice_5_apk.apk!/lib/arm64-v8a, /data/app/org.linphone.debug-CVQDk_vyR43pPaiIVZo3aw==/split_lib_slice_6_apk.apk!/lib/arm64-v8a, /data/app/org.linphone.debug-CVQDk_vyR43pPaiIVZo3aw==/split_lib_slice_7_apk.apk!/lib/arm64-v8a, /data/app/org.linphone.debug-CVQDk_vyR43pPaiIVZo3aw==/split_lib_slice_8_apk.apk!/lib/arm64-v8a, /data/app/org.linphone.debug-CVQDk_vyR43pPaiIVZo3aw==/split_lib_slice_9_apk.apk!/lib/arm64-v8a, /system/lib64, /system/vendor/lib64]]
2019-09-16 12:16:22.616 12992-12992/org.linphone.debug E/AndroidRuntime:     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.view.LayoutInflater.createView(LayoutInflater.java:606)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:790)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:866)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:866)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
        at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:555)
        at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:161)
        at org.linphone.call.CallActivity.onCreate(CallActivity.java:141)
        at android.app.Activity.performCreate(Activity.java:7021)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1219)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2777)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2899)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1600)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6610)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
    	Suppressed: java.io.IOException: No original dex files found for dex location /data/app/org.linphone.debug-CVQDk_vyR43pPaiIVZo3aw==/split_lib_resources_apk.apk
        at dalvik.system.DexFile.openDexFileNative(Native Method)
        at dalvik.system.DexFile.openDexFile(DexFile.java:353)
        at dalvik.system.DexFile.<init>(DexFile.java:100)
        at dalvik.system.DexFile.<init>(DexFile.java:74)
        at dalvik.system.DexPathList.loadDexFile(DexPathList.java:374)
        at dalvik.system.DexPathList.makeDexElements(DexPathList.java:337)
        at dalvik.system.DexPathList.<init>(DexPathList.java:157)
        at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:65)
        at dalvik.system.PathClassLoader.<init>(PathClassLoader.java:64)
        at com.android.internal.os.PathClassLoaderFactory.createClassLoader(PathClassLoaderFactory.java:43)
        at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:69)
        at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:36)
        at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:676)
        at android.app.LoadedApk.getClassLoader(LoadedApk.java:709)
        at android.app.LoadedApk.getResources(LoadedApk.java:936)
        at android.app.ContextImpl.createAppContext(ContextImpl.java:2251)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5723)
        at android.app.ActivityThread.-wrap1(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1668)
        		... 6 more

**Comment by Viish** [comment]
This happens because you updated the app but not the SDK.

**Comment by wirelessmundi** [comment]
ok, i  wasn't using sdk directly.. compile it now. Thanks.

**Comment by wirelessmundi** [comment]
sorry, i just update and compile the SDK and i got the same error... what could i be doing wrong?

**Comment by Viish** [comment]
I bet you didn't update the submodules:
`git submodule update --recursive` in linphone-sdk
You can also use the one from our maven repository:
https://linphone.org/snapshots/maven_repository/org/linphone/linphone-sdk-android/4.2-131-g45180ef/

**Comment by wirelessmundi** [comment]
yes i did that :). gonna try the maven version. 

i must have something wrong in android studio, i clean, rebuild de project but in the about screen is not showing the same git version, it shows an old version:

![Screenshot_2019-09-16-14-08-41](https://user-images.githubusercontent.com/13020619/64956741-939b6800-d88b-11e9-95e1-11eac097ad24.jpg)

It there any other tip to build in android studio?
I've set the correct path:
ls -l linphone-sdk-android/
total 16
-rw-r--r--  1 antonio  staff   433 Sep 16 12:38 build.gradle
lrwxr-xr-x  1 antonio  staff    93 Sep 16 13:24 linphone-sdk-android-debug.aar -> /Users/antonio/linphone-sdk/build/linphone-sdk/bin/outputs/aar/linphone-sdk-android-debug.aar
lrwxr-xr-x  1 antonio  staff    95 Sep 16 13:24 linphone-sdk-android-release.aar -> /Users/antonio/linphone-sdk/build/linphone-sdk/bin/outputs/aar/linphone-sdk-android-release.aar
-rw-r--r--  1 antonio  staff  1124 Sep 13 11:50 linphone-sdk-android.iml

**Comment by Viish** [comment]
Your setup looks OK, I don't know why it doesn't uses your local build.

**Comment by wirelessmundi** [comment]
true.. don't get why... anyway i force the snapshot url and its ok. Thanks. i can continue debugging the stun issue.
