### ISSUE TITLE
dlopen failed: cannot locate symbol "ms_video_find_best_configuration_for_bitrate"

### ISSUE THREAD

**Issue by farrukh-obaid** [BelledonneCommunications/linphone-android#84]
I downloaded 1 July 2017 latest build and getting this error on initialization
 
07-02 12:04:55.419 2974-2992/fo.com.myapplication E/EGL_emulation: tid 2992: eglSurfaceAttrib(1174): error 0x3009 (EGL_BAD_MATCH)
07-02 12:06:29.412 2974-2974/fo.com.myapplication E/AndroidRuntime: FATAL EXCEPTION: main
                                                                    Process: fo.com.myapplication, PID: 2974
                                                                    java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "ms_video_find_best_configuration_for_bitrate" referenced by "/data/app/fo.com.myapplication-1/lib/x86/libmediastreamer_voip.so"...
                                                                        at java.lang.Runtime.loadLibrary0(Runtime.java:989)
                                                                        at java.lang.System.loadLibrary(System.java:1530)
                                                                        at org.linphone.core.LinphoneCoreFactoryImpl.<clinit>(LinphoneCoreFactoryImpl.java:51)
                                                                        at java.lang.Class.classForName(Native Method)
                                                                        at java.lang.Class.forName(Class.java:400)
                                                                        at java.lang.Class.forName(Class.java:326)
                                                                        at org.linphone.core.LinphoneCoreFactory.instance(LinphoneCoreFactory.java:47)
                                                                        at fo.com.myapplication.MainActivity$1.onClick(MainActivity.java:22)
                                                                        at android.view.View.performClick(View.java:5637)
                                                                        at android.view.View$PerformClick.run(View.java:22429)
                                                                        at android.os.Handler.handleCallback(Handler.java:751)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                        at android.os.Looper.loop(Looper.java:154)
                                                                        at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

**Comment by CrabeMan** [comment]
Hello,
Did you compile it ? If yes, have you not forget to enable video in the prepare cli ?
```./prepare.py -DENABLE_VIDEO=ON -DENABLE_FFMPEG=ON -DENABLE_X264=ON```

Did you import mediastreamer2 java interface ?
This [method](https://github.com/BelledonneCommunications/linphone-android/blob/master/src/android/org/linphone/LinphoneManager.java#L240) can help you.

CrabeMan.

**Comment by farrukh-obaid** [comment]
I downloaded zip file from here https://www.linphone.org/snapshots/android/
file name was **liblinphone-android-sdk-latest.zip** 1 July build. I imported .aar in android studio and just added this single line
**LinphoneCoreFactory.instance().setDebugMode(true, "Linphone Mini");**
and getting this exception

**Comment by farrukh-obaid** [comment]
just download latest 5 July Build same crash
