### ISSUE TITLE
App crashes on startup if run in emulator inside a system that doesn't have Bluetooth

### ISSUE THREAD

**Issue by zsubzwary** [BelledonneCommunications/linphone-android#878]
After cloning the project and running it in emulator the application crashed on startup, after reading the logcat I realized that the issue was in Compatibility.java file in the code `String name = BluetoothAdapter.getDefaultAdapter().getName();`, my system does not have Bluetooth in it, so this might be because of that, I am not sure.
The same code works fine on a real physical device.

Following is the output from the logcat after the crash:

```
2019-12-19 15:09:40.250 6913-6913/? I/art: Not late-enabling -Xcheck:jni (already on)
2019-12-19 15:09:40.250 6913-6913/? W/art: Unexpected CPU variant for X86 using defaults: x86
2019-12-19 15:09:40.461 6913-6913/org.linphone.debug I/FirebaseInitProvider: FirebaseApp initialization successful
2019-12-19 15:09:40.642 6913-6913/org.linphone.debug W/FactoryImpl: Unable to load optional library ffmpeg-linphone: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/org.linphone.debug-1/base.apk"],nativeLibraryDirectories=[/data/app/org.linphone.debug-1/lib/x86, /data/app/org.linphone.debug-1/base.apk!/lib/x86, /system/lib, /vendor/lib]]] couldn't find "libffmpeg-linphone.so"
2019-12-19 15:09:40.774 6913-6913/org.linphone.debug E/BluetoothAdapter: Bluetooth binder is null
2019-12-19 15:09:40.775 6913-6913/org.linphone.debug D/AndroidRuntime: Shutting down VM
    
    
    --------- beginning of crash
2019-12-19 15:09:40.775 6913-6913/org.linphone.debug E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.linphone.debug, PID: 6913
    java.lang.RuntimeException: Unable to create service org.linphone.service.LinphoneService: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.bluetooth.BluetoothAdapter.getName()' on a null object reference
        at android.app.ActivityThread.handleCreateService(ActivityThread.java:3172)
        at android.app.ActivityThread.-wrap5(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1550)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6077)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.bluetooth.BluetoothAdapter.getName()' on a null object reference
        at org.linphone.compatibility.Compatibility.getDeviceName(Compatibility.java:56)
        at org.linphone.LinphoneContext.dumpDeviceInformation(LinphoneContext.java:290)
        at org.linphone.LinphoneContext.<init>(LinphoneContext.java:106)
        at org.linphone.service.LinphoneService.onCreate(LinphoneService.java:56)
        at android.app.ActivityThread.handleCreateService(ActivityThread.java:3162)
        at android.app.ActivityThread.-wrap5(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1550) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6077) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756) 

```

**Comment by Viish** [comment]
Thanks, I'll fix it.

**Comment by zsubzwary** [comment]
You are welcome, I hope you do it fast though 😅 because I will be waiting !!

**Comment by Viish** [comment]
Hi,
I fixed the issue in both master and release/4.2 branches.
Cheers,

**Comment by pergolafabio** [comment]
hey @Viish , i was usng linhome, and i receive the same error, what did you fix in the code? maybe i can do the same for Linhome

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.linhome, PID: 4248
    java.lang.RuntimeException: Unable to create application org.linhome.LinhomeApplication: java.lang.NullPointerException: BluetoothAdapter.getDefaultAdapter() must not be null
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4710)
        at android.app.ActivityThread.-wrap1(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5417)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
     Caused by: java.lang.NullPointerException: BluetoothAdapter.getDefaultAdapter() must not be null
        at org.linhome.compatibility.Api23Compatibility$Companion.getDeviceName(Api23Compatibility.kt:37)
        at org.linphone.compatibility.Compatibility$Companion.getDeviceName(Compatibility.kt:62)
        at org.linhome.linphonecore.CorePreferences.getDeviceName(CorePreferences.kt:110)
        at org.linhome.linphonecore.CoreContext.computeUserAgent(CoreContext.kt:258)
        at org.linhome.linphonecore.CoreContext.configureCore(CoreContext.kt:252)
        at org.linhome.linphonecore.CoreContext.start(CoreContext.kt:221)
        at org.linhome.linphonecore.CoreContext.start$default(CoreContext.kt:208)
        at org.linhome.LinhomeApplication$Companion.ensureCoreExists(LinhomeApplication.kt:66)
        at org.linhome.LinhomeApplication.onCreate(LinhomeApplication.kt:106)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1013)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4707)
        at android.app.ActivityThread.-wrap1(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:148) 
        at android.app.ActivityThread.main(ActivityThread.java:5417) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 

```

**Comment by Viish** [comment]
Try with 8dfbe983967b30e31e22fdbf28ab85fbdfa76e1a

**Comment by pergolafabio** [comment]
ok, will do it later, i also removed the bluetooth from the compatibility java file , that did trick too
but when i start now linhome on emulator, i'm missing a lof of text/buttons?
what cloud be wrong?

![image](https://user-images.githubusercontent.com/43251136/150129689-507adc25-fe1b-4b71-98c9-e77d62961012.png)

**Comment by pergolafabio** [comment]
where do i find : 8dfbe983967b30e31e22fdbf28ab85fbdfa76e1a btw ?
can i see it here? https://gitlab.linphone.org/BC/public/linhome-android

**Comment by Viish** [comment]
It's on linphone-android repository, on release/4.6 branch.

**Comment by pergolafabio** [comment]
ok, found it , but i'm using linhome :-)

but i'll have a look for a proper way and adapt code
any idea about the missing text/buttons/theme?

**Comment by Viish** [comment]
No, probably a build error. Clean and rebuild it.

**Comment by pergolafabio** [comment]
hmm, tried that already :-(
