### ISSUE TITLE
Crash at the beginning

### ISSUE THREAD

**Issue by nzkar** [BelledonneCommunications/linphone-android#924]
Hi, linphone-android crashes with the debugger log provided below with each run from the android studio. The crash log points the line "Factory.instance().setLogCollectionPath(context.getFilesDir().getAbsolutePath());"

2020-02-20 15:56:37.542 2369-2369/org.linphone.debug I/System.out: waiting for debugger to settle...
2020-02-20 15:56:37.944 2369-2369/org.linphone.debug I/chatty: uid=10106(org.linphone.debug) identical 2 lines
2020-02-20 15:56:38.146 2369-2369/org.linphone.debug I/System.out: waiting for debugger to settle...
2020-02-20 15:56:38.346 2369-2369/org.linphone.debug I/System.out: waiting for debugger to settle...
2020-02-20 15:56:38.748 2369-2369/org.linphone.debug I/chatty: uid=10106(org.linphone.debug) identical 2 lines
2020-02-20 15:56:38.949 2369-2369/org.linphone.debug I/System.out: waiting for debugger to settle...
2020-02-20 15:56:39.150 2369-2369/org.linphone.debug I/System.out: debugger has settled (1353)
2020-02-20 15:56:39.844 2369-2369/org.linphone.debug I/FirebaseInitProvider: FirebaseApp initialization successful
2020-02-20 15:56:40.342 2369-2369/org.linphone.debug D/ResolutionTunerAppList: loadTunerAppList + 
2020-02-20 15:56:40.343 2369-2369/org.linphone.debug E/ResolutionTunerAppList: Target file doesn't exist: system/vendor/etc/sf_resolution_tuner_app_list.xml
2020-02-20 15:56:40.344 2369-2369/org.linphone.debug D/SurfaceExt: SurfaceExtimpl, mPackageName:org.linphone.debug,mContainPackageName:false
2020-02-20 15:56:40.345 2369-2369/org.linphone.debug I/SurfaceFactory: [static] sSurfaceFactory = com.mediatek.view.impl.SurfaceFactoryImpl@c4348ef
2020-02-20 15:56:40.345 2369-2369/org.linphone.debug D/OpenGLRenderer: Skia GL Pipeline
2020-02-20 15:56:40.380 2369-2369/org.linphone.debug D/ViewRootImpl[LinphoneLauncherActivity]: hardware acceleration = true , fakeHwAccelerated = false, sRendererDisabled = false, forceHwAccelerated = false, sSystemRendererDisabled = false
2020-02-20 15:56:40.397 2369-2369/org.linphone.debug V/PhoneWindow: DecorView setVisiblity: visibility = 0, Parent = android.view.ViewRootImpl@8d93cda, this = DecorView@fa5850b[LinphoneLauncherActivity]
2020-02-20 15:56:40.473 2369-2369/org.linphone.debug D/AndroidRuntime: Shutting down VM
2020-02-20 15:56:40.485 2369-2369/org.linphone.debug E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.linphone.debug, PID: 2369
    java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/org.linphone.debug-Gi7gf6ErvjLRpN3sFIQ-KA==/base.apk"],nativeLibraryDirectories=[/data/app/org.linphone.debug-Gi7gf6ErvjLRpN3sFIQ-KA==/lib/arm64, /data/app/org.linphone.debug-Gi7gf6ErvjLRpN3sFIQ-KA==/base.apk!/lib/arm64-v8a, /system/lib64]]] couldn't find "libc++_shared.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1012)
        at java.lang.System.loadLibrary(System.java:1669)
        at org.linphone.core.FactoryImpl.<clinit>(Factory.java:444)
        at org.linphone.core.Factory.instance(Factory.java:46)
        at org.linphone.LinphoneContext.<init>(LinphoneContext.java:101)
        at org.linphone.service.LinphoneService.onCreate(LinphoneService.java:56)
        at android.app.ActivityThread.handleCreateService(ActivityThread.java:3563)
        at android.app.ActivityThread.access$1400(ActivityThread.java:206)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1694)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6702)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:911)
2020-02-20 15:57:09.890 2369-2433/org.linphone.debug E/FirebaseInstanceId: Token retrieval failed without exception message. Will retry token retrieval
2020-02-20 15:57:10.411 2369-2437/org.linphone.debug W/MessengerIpcClient: Timing out request: 1
2020-02-20 15:58:09.917 2369-2433/org.linphone.debug E/FirebaseInstanceId: Token retrieval failed without exception message. Will retry token retrieval

**Comment by Viish** [comment]
In Android Studio, Build -> Clean project and build again.
