### ISSUE TITLE
Contacts sort crash

### ISSUE THREAD

**Issue by nzkar** [BelledonneCommunications/linphone-android#926]
Hi, my application crashes when I have approximately 1000 contacts with the log given below. The cause of the crash is "Collections.sort(data.contacts);" in AsyncContactsLoader.java class. If I comment this out, it doesn't crash. However, if it is not comment out, the app crash at each start (so never successfully launches again).

2020-02-21 10:13:25.476 12259-12371/org.linphone.debug E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
    Process: org.linphone.debug, PID: 12259
    java.lang.RuntimeException: An error occurred while executing doInBackground()
        at android.os.AsyncTask$3.done(AsyncTask.java:354)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
        at java.util.concurrent.FutureTask.run(FutureTask.java:271)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.lang.IllegalArgumentException: Comparison method violates its general contract!
        at java.util.ComparableTimSort.mergeHi(ComparableTimSort.java:866)
        at java.util.ComparableTimSort.mergeAt(ComparableTimSort.java:483)
        at java.util.ComparableTimSort.mergeCollapse(ComparableTimSort.java:406)
        at java.util.ComparableTimSort.sort(ComparableTimSort.java:213)
        at java.util.Arrays.sort(Arrays.java:1312)
        at java.util.Arrays.sort(Arrays.java:1491)
        at java.util.ArrayList.sort(ArrayList.java:1470)
        at java.util.Collections.sort(Collections.java:201)
        at java.util.Collections.sort(Collections.java:156)
        at org.linphone.contacts.AsyncContactsLoader.doInBackground(AsyncContactsLoader.java:259)
        at org.linphone.contacts.AsyncContactsLoader.doInBackground(AsyncContactsLoader.java:45)
        at android.os.AsyncTask$2.call(AsyncTask.java:333)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:764) 
    
    
    --------- beginning of system
2020-02-21 10:13:25.878 12259-12296/org.linphone.debug D/Surface: Surface::disconnect(this=0x7471abd000,api=1)
2020-02-21 10:13:25.989 12259-12259/org.linphone.debug V/PhoneWindow: DecorView setVisiblity: visibility = 4, Parent = android.view.ViewRootImpl@39d54e2, this = DecorView@3d08dd7[DialerActivity]
2020-02-21 10:13:26.127 12259-12259/org.linphone.debug D/View: [Warning] assignParent to null: this = DecorView@3d08dd7[DialerActivity]

**Comment by Viish** [comment]
This happens because of the compareTo() method of LinphoneContact that returns -1 sometimes.
See https://stackoverflow.com/questions/19325256/java-lang-illegalargumentexception-comparison-method-violates-its-general-contr
If you have a patch I'll gradly merge it.

**Comment by Viish** [comment]
Hi,
Can you try commit 2d5ddf869d83a0cdc02e1497e8742d2dab739908 ?
It should solve your issue.

**Comment by nzkar** [comment]
It solved the problem, thank you.
