### ISSUE TITLE
CameraBase: Camera service died!

### ISSUE THREAD

**Issue by yufengjinlin** [BelledonneCommunications/linphone-android#993]
2020-04-29 14:34:25.575 25079-25174/? D/ACodec: onAllocateComponent
2020-04-29 14:34:25.576 25079-25174/? I/OMXClient: MuxOMX ctor
2020-04-29 14:34:27.469 25079-25079/org.linphone.debug W/CameraBase: An error occurred while connecting to camera 2: Service not available
2020-04-29 14:34:27.470 25079-25079/org.linphone.debug W/System.err: java.lang.RuntimeException: Fail to connect to camera service
2020-04-29 14:34:27.471 25079-25079/org.linphone.debug W/System.err:     at android.hardware.Camera.<init>(Camera.java:499)
2020-04-29 14:34:27.471 25079-25079/org.linphone.debug W/System.err:     at android.hardware.Camera.open(Camera.java:348)
2020-04-29 14:34:27.471 25079-25079/org.linphone.debug W/System.err:     at org.linphone.mediastream.video.capture.hwconf.AndroidCameraConfigurationReader9.probeCameras(AndroidCameraConfigurationReader9.java:40)
2020-04-29 14:34:27.471 25079-25079/org.linphone.debug W/System.err:     at org.linphone.mediastream.video.capture.hwconf.AndroidCameraConfiguration.probeCamerasSDK9(AndroidCameraConfiguration.java:82)
2020-04-29 14:34:27.471 25079-25079/org.linphone.debug W/System.err:     at org.linphone.mediastream.video.capture.hwconf.AndroidCameraConfiguration.initCamerasCache(AndroidCameraConfiguration.java:67)
2020-04-29 14:34:27.471 25079-25079/org.linphone.debug W/System.err:     at org.linphone.mediastream.video.capture.hwconf.AndroidCameraConfiguration.retrieveCameras(AndroidCameraConfiguration.java:35)
2020-04-29 14:34:27.471 25079-25079/org.linphone.debug W/System.err:     at org.linphone.mediastream.video.capture.AndroidVideoApi5JniWrapper.detectCamerasCount(AndroidVideoApi5JniWrapper.java:46)
2020-04-29 14:34:27.472 25079-25079/org.linphone.debug W/System.err:     at org.linphone.mediastream.video.capture.AndroidVideoApi9JniWrapper.detectCamerasCount(AndroidVideoApi9JniWrapper.java:37)
2020-04-29 14:34:27.472 25079-25079/org.linphone.debug W/System.err:     at org.linphone.core.FactoryImpl.createCore3(Native Method)
2020-04-29 14:34:27.472 25079-25079/org.linphone.debug W/System.err:     at org.linphone.core.FactoryImpl.createCore(Factory.java:520)
2020-04-29 14:34:27.472 25079-25079/org.linphone.debug W/System.err:     at org.linphone.LinphoneManager.startLibLinphone(LinphoneManager.java:407)
2020-04-29 14:34:27.472 25079-25079/org.linphone.debug W/System.err:     at org.linphone.LinphoneContext.start(LinphoneContext.java:207)
2020-04-29 14:34:27.472 25079-25079/org.linphone.debug W/System.err:     at org.linphone.service.LinphoneService.onStartCommand(LinphoneService.java:90)
2020-04-29 14:34:27.472 25079-25079/org.linphone.debug W/System.err:     at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3326)
2020-04-29 14:34:27.472 25079-25079/org.linphone.debug W/System.err:     at android.app.ActivityThread.-wrap21(ActivityThread.java)
2020-04-29 14:34:27.472 25079-25079/org.linphone.debug W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1582)
2020-04-29 14:34:27.472 25079-25079/org.linphone.debug W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
2020-04-29 14:34:27.473 25079-25079/org.linphone.debug W/System.err:     at android.os.Looper.loop(Looper.java:154)
2020-04-29 14:34:27.473 25079-25079/org.linphone.debug W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6119)
2020-04-29 14:34:27.473 25079-25079/org.linphone.debug W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2020-04-29 14:34:27.473 25079-25079/org.linphone.debug W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:982)
2020-04-29 14:34:27.473 25079-25079/org.linphone.debug W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:872)
2020-04-29 14:34:27.474 25079-25079/org.linphone.debug E/CameraBase: Error reading number of cameras: Status(-129): '-32: '
2020-04-29 14:34:27.474 25079-25079/org.linphone.debug E/CameraBase: Error reading number of cameras: Status(-129): '-32: '
2020-04-29 14:34:27.487 25079-25182/org.linphone.debug W/CameraBase: Camera service died!

**Comment by Viish** [comment]
The camera service is part of Android OS, we merely use it.
Reboot your device, it should fix the problem.
